// Code generated by go-swagger; DO NOT EDIT.

package edge_configs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEdgeConfigFilesParams creates a new EdgeConfigFilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEdgeConfigFilesParams() *EdgeConfigFilesParams {
	return &EdgeConfigFilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEdgeConfigFilesParamsWithTimeout creates a new EdgeConfigFilesParams object
// with the ability to set a timeout on a request.
func NewEdgeConfigFilesParamsWithTimeout(timeout time.Duration) *EdgeConfigFilesParams {
	return &EdgeConfigFilesParams{
		timeout: timeout,
	}
}

// NewEdgeConfigFilesParamsWithContext creates a new EdgeConfigFilesParams object
// with the ability to set a context for a request.
func NewEdgeConfigFilesParamsWithContext(ctx context.Context) *EdgeConfigFilesParams {
	return &EdgeConfigFilesParams{
		Context: ctx,
	}
}

// NewEdgeConfigFilesParamsWithHTTPClient creates a new EdgeConfigFilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewEdgeConfigFilesParamsWithHTTPClient(client *http.Client) *EdgeConfigFilesParams {
	return &EdgeConfigFilesParams{
		HTTPClient: client,
	}
}

/*
EdgeConfigFilesParams contains all the parameters to send to the API endpoint

	for the edge config files operation.

	Typically these are written to a http.Request.
*/
type EdgeConfigFilesParams struct {

	/* ID.

	   Edge configuration identifier
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the edge config files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EdgeConfigFilesParams) WithDefaults() *EdgeConfigFilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the edge config files params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EdgeConfigFilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the edge config files params
func (o *EdgeConfigFilesParams) WithTimeout(timeout time.Duration) *EdgeConfigFilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the edge config files params
func (o *EdgeConfigFilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the edge config files params
func (o *EdgeConfigFilesParams) WithContext(ctx context.Context) *EdgeConfigFilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the edge config files params
func (o *EdgeConfigFilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the edge config files params
func (o *EdgeConfigFilesParams) WithHTTPClient(client *http.Client) *EdgeConfigFilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the edge config files params
func (o *EdgeConfigFilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the edge config files params
func (o *EdgeConfigFilesParams) WithID(id int64) *EdgeConfigFilesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the edge config files params
func (o *EdgeConfigFilesParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EdgeConfigFilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
