// Code generated by go-swagger; DO NOT EDIT.

package edge_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/portainer/client-api/models"
)

// EdgeStackInspectReader is a Reader for the EdgeStackInspect structure.
type EdgeStackInspectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EdgeStackInspectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewEdgeStackInspectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEdgeStackInspectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEdgeStackInspectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewEdgeStackInspectServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEdgeStackInspectOK creates a EdgeStackInspectOK with default headers values
func NewEdgeStackInspectOK() *EdgeStackInspectOK {
	return &EdgeStackInspectOK{}
}

/* EdgeStackInspectOK describes a response with status code 200, with default header values.

OK
*/
type EdgeStackInspectOK struct {
	Payload *models.PortainerEdgeStack
}

func (o *EdgeStackInspectOK) Error() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}][%d] edgeStackInspectOK  %+v", 200, o.Payload)
}
func (o *EdgeStackInspectOK) GetPayload() *models.PortainerEdgeStack {
	return o.Payload
}

func (o *EdgeStackInspectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PortainerEdgeStack)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEdgeStackInspectBadRequest creates a EdgeStackInspectBadRequest with default headers values
func NewEdgeStackInspectBadRequest() *EdgeStackInspectBadRequest {
	return &EdgeStackInspectBadRequest{}
}

/* EdgeStackInspectBadRequest describes a response with status code 400, with default header values.

EdgeStackInspectBadRequest edge stack inspect bad request
*/
type EdgeStackInspectBadRequest struct {
}

func (o *EdgeStackInspectBadRequest) Error() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}][%d] edgeStackInspectBadRequest ", 400)
}

func (o *EdgeStackInspectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeStackInspectInternalServerError creates a EdgeStackInspectInternalServerError with default headers values
func NewEdgeStackInspectInternalServerError() *EdgeStackInspectInternalServerError {
	return &EdgeStackInspectInternalServerError{}
}

/* EdgeStackInspectInternalServerError describes a response with status code 500, with default header values.

EdgeStackInspectInternalServerError edge stack inspect internal server error
*/
type EdgeStackInspectInternalServerError struct {
}

func (o *EdgeStackInspectInternalServerError) Error() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}][%d] edgeStackInspectInternalServerError ", 500)
}

func (o *EdgeStackInspectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEdgeStackInspectServiceUnavailable creates a EdgeStackInspectServiceUnavailable with default headers values
func NewEdgeStackInspectServiceUnavailable() *EdgeStackInspectServiceUnavailable {
	return &EdgeStackInspectServiceUnavailable{}
}

/* EdgeStackInspectServiceUnavailable describes a response with status code 503, with default header values.

Edge compute features are disabled
*/
type EdgeStackInspectServiceUnavailable struct {
}

func (o *EdgeStackInspectServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /edge_stacks/{id}][%d] edgeStackInspectServiceUnavailable ", 503)
}

func (o *EdgeStackInspectServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
