// Code generated by go-swagger; DO NOT EDIT.

package edge_stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEdgeStacksParams creates a new GetEdgeStacksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEdgeStacksParams() *GetEdgeStacksParams {
	return &GetEdgeStacksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEdgeStacksParamsWithTimeout creates a new GetEdgeStacksParams object
// with the ability to set a timeout on a request.
func NewGetEdgeStacksParamsWithTimeout(timeout time.Duration) *GetEdgeStacksParams {
	return &GetEdgeStacksParams{
		timeout: timeout,
	}
}

// NewGetEdgeStacksParamsWithContext creates a new GetEdgeStacksParams object
// with the ability to set a context for a request.
func NewGetEdgeStacksParamsWithContext(ctx context.Context) *GetEdgeStacksParams {
	return &GetEdgeStacksParams{
		Context: ctx,
	}
}

// NewGetEdgeStacksParamsWithHTTPClient creates a new GetEdgeStacksParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEdgeStacksParamsWithHTTPClient(client *http.Client) *GetEdgeStacksParams {
	return &GetEdgeStacksParams{
		HTTPClient: client,
	}
}

/* GetEdgeStacksParams contains all the parameters to send to the API endpoint
   for the get edge stacks operation.

   Typically these are written to a http.Request.
*/
type GetEdgeStacksParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get edge stacks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEdgeStacksParams) WithDefaults() *GetEdgeStacksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get edge stacks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEdgeStacksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get edge stacks params
func (o *GetEdgeStacksParams) WithTimeout(timeout time.Duration) *GetEdgeStacksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get edge stacks params
func (o *GetEdgeStacksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get edge stacks params
func (o *GetEdgeStacksParams) WithContext(ctx context.Context) *GetEdgeStacksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get edge stacks params
func (o *GetEdgeStacksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get edge stacks params
func (o *GetEdgeStacksParams) WithHTTPClient(client *http.Client) *GetEdgeStacksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get edge stacks params
func (o *GetEdgeStacksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetEdgeStacksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
