// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ModelsCloudCredentialMap models cloud credential map
//
// swagger:model models.CloudCredentialMap
type ModelsCloudCredentialMap map[string]string

// Validate validates this models cloud credential map
func (m ModelsCloudCredentialMap) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models cloud credential map based on context it is used
func (m ModelsCloudCredentialMap) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
