// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PodsecurityPodSecurityAllowProcMount podsecurity pod security allow proc mount
//
// swagger:model podsecurity.PodSecurityAllowProcMount
type PodsecurityPodSecurityAllowProcMount struct {

	// enabled
	Enabled *bool `json:"enabled,omitempty"`

	// proc mount type
	ProcMountType string `json:"procMountType,omitempty"`
}

// Validate validates this podsecurity pod security allow proc mount
func (m *PodsecurityPodSecurityAllowProcMount) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this podsecurity pod security allow proc mount based on context it is used
func (m *PodsecurityPodSecurityAllowProcMount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PodsecurityPodSecurityAllowProcMount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PodsecurityPodSecurityAllowProcMount) UnmarshalBinary(b []byte) error {
	var res PodsecurityPodSecurityAllowProcMount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
