// Code generated by go-swagger; DO NOT EDIT.

package helm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewHelmGetHistoryParams creates a new HelmGetHistoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHelmGetHistoryParams() *HelmGetHistoryParams {
	return &HelmGetHistoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHelmGetHistoryParamsWithTimeout creates a new HelmGetHistoryParams object
// with the ability to set a timeout on a request.
func NewHelmGetHistoryParamsWithTimeout(timeout time.Duration) *HelmGetHistoryParams {
	return &HelmGetHistoryParams{
		timeout: timeout,
	}
}

// NewHelmGetHistoryParamsWithContext creates a new HelmGetHistoryParams object
// with the ability to set a context for a request.
func NewHelmGetHistoryParamsWithContext(ctx context.Context) *HelmGetHistoryParams {
	return &HelmGetHistoryParams{
		Context: ctx,
	}
}

// NewHelmGetHistoryParamsWithHTTPClient creates a new HelmGetHistoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewHelmGetHistoryParamsWithHTTPClient(client *http.Client) *HelmGetHistoryParams {
	return &HelmGetHistoryParams{
		HTTPClient: client,
	}
}

/*
HelmGetHistoryParams contains all the parameters to send to the API endpoint

	for the helm get history operation.

	Typically these are written to a http.Request.
*/
type HelmGetHistoryParams struct {

	/* ID.

	   Environment(Endpoint) identifier
	*/
	ID int64

	/* Name.

	   Helm release name
	*/
	Name string

	/* Namespace.

	   specify an optional namespace
	*/
	Namespace *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the helm get history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HelmGetHistoryParams) WithDefaults() *HelmGetHistoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the helm get history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HelmGetHistoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the helm get history params
func (o *HelmGetHistoryParams) WithTimeout(timeout time.Duration) *HelmGetHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the helm get history params
func (o *HelmGetHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the helm get history params
func (o *HelmGetHistoryParams) WithContext(ctx context.Context) *HelmGetHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the helm get history params
func (o *HelmGetHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the helm get history params
func (o *HelmGetHistoryParams) WithHTTPClient(client *http.Client) *HelmGetHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the helm get history params
func (o *HelmGetHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the helm get history params
func (o *HelmGetHistoryParams) WithID(id int64) *HelmGetHistoryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the helm get history params
func (o *HelmGetHistoryParams) SetID(id int64) {
	o.ID = id
}

// WithName adds the name to the helm get history params
func (o *HelmGetHistoryParams) WithName(name string) *HelmGetHistoryParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the helm get history params
func (o *HelmGetHistoryParams) SetName(name string) {
	o.Name = name
}

// WithNamespace adds the namespace to the helm get history params
func (o *HelmGetHistoryParams) WithNamespace(namespace *string) *HelmGetHistoryParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the helm get history params
func (o *HelmGetHistoryParams) SetNamespace(namespace *string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *HelmGetHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.Namespace != nil {

		// query param namespace
		var qrNamespace string

		if o.Namespace != nil {
			qrNamespace = *o.Namespace
		}
		qNamespace := qrNamespace
		if qNamespace != "" {

			if err := r.SetQueryParam("namespace", qNamespace); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
