// Code generated by go-swagger; DO NOT EDIT.

package registries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/portainer/client-api-go/v2/pkg/models"
)

// NewRegistryPingParams creates a new RegistryPingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRegistryPingParams() *RegistryPingParams {
	return &RegistryPingParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRegistryPingParamsWithTimeout creates a new RegistryPingParams object
// with the ability to set a timeout on a request.
func NewRegistryPingParamsWithTimeout(timeout time.Duration) *RegistryPingParams {
	return &RegistryPingParams{
		timeout: timeout,
	}
}

// NewRegistryPingParamsWithContext creates a new RegistryPingParams object
// with the ability to set a context for a request.
func NewRegistryPingParamsWithContext(ctx context.Context) *RegistryPingParams {
	return &RegistryPingParams{
		Context: ctx,
	}
}

// NewRegistryPingParamsWithHTTPClient creates a new RegistryPingParams object
// with the ability to set a custom HTTPClient for a request.
func NewRegistryPingParamsWithHTTPClient(client *http.Client) *RegistryPingParams {
	return &RegistryPingParams{
		HTTPClient: client,
	}
}

/*
RegistryPingParams contains all the parameters to send to the API endpoint

	for the registry ping operation.

	Typically these are written to a http.Request.
*/
type RegistryPingParams struct {

	/* Body.

	   Registry credentials to test
	*/
	Body *models.RegistriesRegistryPingPayload

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the registry ping params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegistryPingParams) WithDefaults() *RegistryPingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the registry ping params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RegistryPingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the registry ping params
func (o *RegistryPingParams) WithTimeout(timeout time.Duration) *RegistryPingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the registry ping params
func (o *RegistryPingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the registry ping params
func (o *RegistryPingParams) WithContext(ctx context.Context) *RegistryPingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the registry ping params
func (o *RegistryPingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the registry ping params
func (o *RegistryPingParams) WithHTTPClient(client *http.Client) *RegistryPingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the registry ping params
func (o *RegistryPingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the registry ping params
func (o *RegistryPingParams) WithBody(body *models.RegistriesRegistryPingPayload) *RegistryPingParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the registry ping params
func (o *RegistryPingParams) SetBody(body *models.RegistriesRegistryPingPayload) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RegistryPingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
