// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/portainer/client-api-go/ce/v2/models"
)

// SystemStatusReader is a Reader for the SystemStatus structure.
type SystemStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SystemStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSystemStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSystemStatusOK creates a SystemStatusOK with default headers values
func NewSystemStatusOK() *SystemStatusOK {
	return &SystemStatusOK{}
}

/*
SystemStatusOK describes a response with status code 200, with default header values.

Success
*/
type SystemStatusOK struct {
	Payload *models.SystemStatus
}

// IsSuccess returns true when this system status o k response has a 2xx status code
func (o *SystemStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this system status o k response has a 3xx status code
func (o *SystemStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this system status o k response has a 4xx status code
func (o *SystemStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this system status o k response has a 5xx status code
func (o *SystemStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this system status o k response a status code equal to that given
func (o *SystemStatusOK) IsCode(code int) bool {
	return code == 200
}

func (o *SystemStatusOK) Error() string {
	return fmt.Sprintf("[GET /system/status][%d] systemStatusOK  %+v", 200, o.Payload)
}

func (o *SystemStatusOK) String() string {
	return fmt.Sprintf("[GET /system/status][%d] systemStatusOK  %+v", 200, o.Payload)
}

func (o *SystemStatusOK) GetPayload() *models.SystemStatus {
	return o.Payload
}

func (o *SystemStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SystemStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
