// Code generated by go-swagger; DO NOT EDIT.

package helm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewHelmDeleteParams creates a new HelmDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHelmDeleteParams() *HelmDeleteParams {
	return &HelmDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHelmDeleteParamsWithTimeout creates a new HelmDeleteParams object
// with the ability to set a timeout on a request.
func NewHelmDeleteParamsWithTimeout(timeout time.Duration) *HelmDeleteParams {
	return &HelmDeleteParams{
		timeout: timeout,
	}
}

// NewHelmDeleteParamsWithContext creates a new HelmDeleteParams object
// with the ability to set a context for a request.
func NewHelmDeleteParamsWithContext(ctx context.Context) *HelmDeleteParams {
	return &HelmDeleteParams{
		Context: ctx,
	}
}

// NewHelmDeleteParamsWithHTTPClient creates a new HelmDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewHelmDeleteParamsWithHTTPClient(client *http.Client) *HelmDeleteParams {
	return &HelmDeleteParams{
		HTTPClient: client,
	}
}

/* HelmDeleteParams contains all the parameters to send to the API endpoint
   for the helm delete operation.

   Typically these are written to a http.Request.
*/
type HelmDeleteParams struct {

	/* ID.

	   Environment(Endpoint) identifier
	*/
	ID int64

	/* Namespace.

	   An optional namespace
	*/
	Namespace string

	/* Release.

	   The name of the release/application to uninstall
	*/
	Release string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the helm delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HelmDeleteParams) WithDefaults() *HelmDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the helm delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HelmDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the helm delete params
func (o *HelmDeleteParams) WithTimeout(timeout time.Duration) *HelmDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the helm delete params
func (o *HelmDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the helm delete params
func (o *HelmDeleteParams) WithContext(ctx context.Context) *HelmDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the helm delete params
func (o *HelmDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the helm delete params
func (o *HelmDeleteParams) WithHTTPClient(client *http.Client) *HelmDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the helm delete params
func (o *HelmDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the helm delete params
func (o *HelmDeleteParams) WithID(id int64) *HelmDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the helm delete params
func (o *HelmDeleteParams) SetID(id int64) {
	o.ID = id
}

// WithNamespace adds the namespace to the helm delete params
func (o *HelmDeleteParams) WithNamespace(namespace string) *HelmDeleteParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the helm delete params
func (o *HelmDeleteParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithRelease adds the release to the helm delete params
func (o *HelmDeleteParams) WithRelease(release string) *HelmDeleteParams {
	o.SetRelease(release)
	return o
}

// SetRelease adds the release to the helm delete params
func (o *HelmDeleteParams) SetRelease(release string) {
	o.Release = release
}

// WriteToRequest writes these params to a swagger request
func (o *HelmDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// query param namespace
	qrNamespace := o.Namespace
	qNamespace := qrNamespace
	if qNamespace != "" {

		if err := r.SetQueryParam("namespace", qNamespace); err != nil {
			return err
		}
	}

	// path param release
	if err := r.SetPathParam("release", o.Release); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
