// Code generated by go-swagger; DO NOT EDIT.

package helm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new helm API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for helm API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	HelmDelete(params *HelmDeleteParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmDeleteNoContent, error)

	HelmInstall(params *HelmInstallParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmInstallCreated, error)

	HelmList(params *HelmListParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmListOK, error)

	HelmRepoSearch(params *HelmRepoSearchParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmRepoSearchOK, error)

	HelmShow(params *HelmShowParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmShowOK, error)

	HelmUserRepositoriesList(params *HelmUserRepositoriesListParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmUserRepositoriesListOK, error)

	HelmUserRepositoryCreate(params *HelmUserRepositoryCreateParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmUserRepositoryCreateOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
HelmDelete deletes helm release

**Access policy**: authenticated
*/
func (a *Client) HelmDelete(params *HelmDeleteParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmDeleteNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHelmDeleteParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "HelmDelete",
		Method:             "DELETE",
		PathPattern:        "/endpoints/{id}/kubernetes/helm/{release}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &HelmDeleteReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*HelmDeleteNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for HelmDelete: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
HelmInstall installs helm chart

**Access policy**: authenticated
*/
func (a *Client) HelmInstall(params *HelmInstallParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmInstallCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHelmInstallParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "HelmInstall",
		Method:             "POST",
		PathPattern:        "/endpoints/{id}/kubernetes/helm",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &HelmInstallReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*HelmInstallCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for HelmInstall: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
HelmList lists helm releases

**Access policy**: authenticated
*/
func (a *Client) HelmList(params *HelmListParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHelmListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "HelmList",
		Method:             "GET",
		PathPattern:        "/endpoints/{id}/kubernetes/helm",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &HelmListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*HelmListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for HelmList: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
HelmRepoSearch searches helm charts

**Access policy**: authenticated
*/
func (a *Client) HelmRepoSearch(params *HelmRepoSearchParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmRepoSearchOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHelmRepoSearchParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "HelmRepoSearch",
		Method:             "GET",
		PathPattern:        "/templates/helm",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &HelmRepoSearchReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*HelmRepoSearchOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for HelmRepoSearch: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
HelmShow shows helm chart information

**Access policy**: authenticated
*/
func (a *Client) HelmShow(params *HelmShowParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmShowOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHelmShowParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "HelmShow",
		Method:             "GET",
		PathPattern:        "/templates/helm/{command}",
		ProducesMediaTypes: []string{"text/plain"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &HelmShowReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*HelmShowOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for HelmShow: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	HelmUserRepositoriesList lists a users helm repositories

	Inspect a user helm repositories.

**Access policy**: authenticated
*/
func (a *Client) HelmUserRepositoriesList(params *HelmUserRepositoriesListParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmUserRepositoriesListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHelmUserRepositoriesListParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "HelmUserRepositoriesList",
		Method:             "GET",
		PathPattern:        "/endpoints/{id}/kubernetes/helm/repositories",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &HelmUserRepositoriesListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*HelmUserRepositoriesListOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for HelmUserRepositoriesList: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
	HelmUserRepositoryCreate creates a user helm repository

	Create a user helm repository.

**Access policy**: authenticated
*/
func (a *Client) HelmUserRepositoryCreate(params *HelmUserRepositoryCreateParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*HelmUserRepositoryCreateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewHelmUserRepositoryCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "HelmUserRepositoryCreate",
		Method:             "POST",
		PathPattern:        "/endpoints/{id}/kubernetes/helm/repositories",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &HelmUserRepositoryCreateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*HelmUserRepositoryCreateOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for HelmUserRepositoryCreate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
