// Code generated by go-swagger; DO NOT EDIT.

package templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/portainer/client-api/models"
)

// NewTemplateFileParams creates a new TemplateFileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTemplateFileParams() *TemplateFileParams {
	return &TemplateFileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewTemplateFileParamsWithTimeout creates a new TemplateFileParams object
// with the ability to set a timeout on a request.
func NewTemplateFileParamsWithTimeout(timeout time.Duration) *TemplateFileParams {
	return &TemplateFileParams{
		timeout: timeout,
	}
}

// NewTemplateFileParamsWithContext creates a new TemplateFileParams object
// with the ability to set a context for a request.
func NewTemplateFileParamsWithContext(ctx context.Context) *TemplateFileParams {
	return &TemplateFileParams{
		Context: ctx,
	}
}

// NewTemplateFileParamsWithHTTPClient creates a new TemplateFileParams object
// with the ability to set a custom HTTPClient for a request.
func NewTemplateFileParamsWithHTTPClient(client *http.Client) *TemplateFileParams {
	return &TemplateFileParams{
		HTTPClient: client,
	}
}

/* TemplateFileParams contains all the parameters to send to the API endpoint
   for the template file operation.

   Typically these are written to a http.Request.
*/
type TemplateFileParams struct {

	/* Body.

	   File details
	*/
	Body *models.TemplatesFilePayload

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the template file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TemplateFileParams) WithDefaults() *TemplateFileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the template file params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TemplateFileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the template file params
func (o *TemplateFileParams) WithTimeout(timeout time.Duration) *TemplateFileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the template file params
func (o *TemplateFileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the template file params
func (o *TemplateFileParams) WithContext(ctx context.Context) *TemplateFileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the template file params
func (o *TemplateFileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the template file params
func (o *TemplateFileParams) WithHTTPClient(client *http.Client) *TemplateFileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the template file params
func (o *TemplateFileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the template file params
func (o *TemplateFileParams) WithBody(body *models.TemplatesFilePayload) *TemplateFileParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the template file params
func (o *TemplateFileParams) SetBody(body *models.TemplatesFilePayload) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TemplateFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
