// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCurrentUserInspectParams creates a new CurrentUserInspectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCurrentUserInspectParams() *CurrentUserInspectParams {
	return &CurrentUserInspectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCurrentUserInspectParamsWithTimeout creates a new CurrentUserInspectParams object
// with the ability to set a timeout on a request.
func NewCurrentUserInspectParamsWithTimeout(timeout time.Duration) *CurrentUserInspectParams {
	return &CurrentUserInspectParams{
		timeout: timeout,
	}
}

// NewCurrentUserInspectParamsWithContext creates a new CurrentUserInspectParams object
// with the ability to set a context for a request.
func NewCurrentUserInspectParamsWithContext(ctx context.Context) *CurrentUserInspectParams {
	return &CurrentUserInspectParams{
		Context: ctx,
	}
}

// NewCurrentUserInspectParamsWithHTTPClient creates a new CurrentUserInspectParams object
// with the ability to set a custom HTTPClient for a request.
func NewCurrentUserInspectParamsWithHTTPClient(client *http.Client) *CurrentUserInspectParams {
	return &CurrentUserInspectParams{
		HTTPClient: client,
	}
}

/*
CurrentUserInspectParams contains all the parameters to send to the API endpoint

	for the current user inspect operation.

	Typically these are written to a http.Request.
*/
type CurrentUserInspectParams struct {

	/* NoEndpointAuthorizations.

	   Set to true to avoid including the environment authorizations in the response
	*/
	NoEndpointAuthorizations bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the current user inspect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CurrentUserInspectParams) WithDefaults() *CurrentUserInspectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the current user inspect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CurrentUserInspectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the current user inspect params
func (o *CurrentUserInspectParams) WithTimeout(timeout time.Duration) *CurrentUserInspectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the current user inspect params
func (o *CurrentUserInspectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the current user inspect params
func (o *CurrentUserInspectParams) WithContext(ctx context.Context) *CurrentUserInspectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the current user inspect params
func (o *CurrentUserInspectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the current user inspect params
func (o *CurrentUserInspectParams) WithHTTPClient(client *http.Client) *CurrentUserInspectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the current user inspect params
func (o *CurrentUserInspectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNoEndpointAuthorizations adds the noEndpointAuthorizations to the current user inspect params
func (o *CurrentUserInspectParams) WithNoEndpointAuthorizations(noEndpointAuthorizations bool) *CurrentUserInspectParams {
	o.SetNoEndpointAuthorizations(noEndpointAuthorizations)
	return o
}

// SetNoEndpointAuthorizations adds the noEndpointAuthorizations to the current user inspect params
func (o *CurrentUserInspectParams) SetNoEndpointAuthorizations(noEndpointAuthorizations bool) {
	o.NoEndpointAuthorizations = noEndpointAuthorizations
}

// WriteToRequest writes these params to a swagger request
func (o *CurrentUserInspectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param noEndpointAuthorizations
	qrNoEndpointAuthorizations := o.NoEndpointAuthorizations
	qNoEndpointAuthorizations := swag.FormatBool(qrNoEndpointAuthorizations)
	if qNoEndpointAuthorizations != "" {

		if err := r.SetQueryParam("noEndpointAuthorizations", qNoEndpointAuthorizations); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
