// Code generated by go-swagger; DO NOT EDIT.

package backup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewBackupStatusFetchParams creates a new BackupStatusFetchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewBackupStatusFetchParams() *BackupStatusFetchParams {
	return &BackupStatusFetchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewBackupStatusFetchParamsWithTimeout creates a new BackupStatusFetchParams object
// with the ability to set a timeout on a request.
func NewBackupStatusFetchParamsWithTimeout(timeout time.Duration) *BackupStatusFetchParams {
	return &BackupStatusFetchParams{
		timeout: timeout,
	}
}

// NewBackupStatusFetchParamsWithContext creates a new BackupStatusFetchParams object
// with the ability to set a context for a request.
func NewBackupStatusFetchParamsWithContext(ctx context.Context) *BackupStatusFetchParams {
	return &BackupStatusFetchParams{
		Context: ctx,
	}
}

// NewBackupStatusFetchParamsWithHTTPClient creates a new BackupStatusFetchParams object
// with the ability to set a custom HTTPClient for a request.
func NewBackupStatusFetchParamsWithHTTPClient(client *http.Client) *BackupStatusFetchParams {
	return &BackupStatusFetchParams{
		HTTPClient: client,
	}
}

/*
BackupStatusFetchParams contains all the parameters to send to the API endpoint

	for the backup status fetch operation.

	Typically these are written to a http.Request.
*/
type BackupStatusFetchParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the backup status fetch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BackupStatusFetchParams) WithDefaults() *BackupStatusFetchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the backup status fetch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *BackupStatusFetchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the backup status fetch params
func (o *BackupStatusFetchParams) WithTimeout(timeout time.Duration) *BackupStatusFetchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the backup status fetch params
func (o *BackupStatusFetchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the backup status fetch params
func (o *BackupStatusFetchParams) WithContext(ctx context.Context) *BackupStatusFetchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the backup status fetch params
func (o *BackupStatusFetchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the backup status fetch params
func (o *BackupStatusFetchParams) WithHTTPClient(client *http.Client) *BackupStatusFetchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the backup status fetch params
func (o *BackupStatusFetchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *BackupStatusFetchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
