// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/portainer/client-api-go/v2/client/custom_templates"

	"github.com/spf13/cobra"
)

// makeOperationCustomTemplatesCustomTemplateDeleteCmd returns a cmd to handle operation customTemplateDelete
func makeOperationCustomTemplatesCustomTemplateDeleteCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "CustomTemplateDelete",
		Short: `Remove a template.
**Access policy**: authenticated`,
		RunE: runOperationCustomTemplatesCustomTemplateDelete,
	}

	if err := registerOperationCustomTemplatesCustomTemplateDeleteParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationCustomTemplatesCustomTemplateDelete uses cmd flags to call endpoint api
func runOperationCustomTemplatesCustomTemplateDelete(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := custom_templates.NewCustomTemplateDeleteParams()
	if err, _ := retrieveOperationCustomTemplatesCustomTemplateDeleteIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationCustomTemplatesCustomTemplateDeleteResult(appCli.CustomTemplates.CustomTemplateDelete(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationCustomTemplatesCustomTemplateDeleteParamFlags registers all flags needed to fill params
func registerOperationCustomTemplatesCustomTemplateDeleteParamFlags(cmd *cobra.Command) error {
	if err := registerOperationCustomTemplatesCustomTemplateDeleteIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationCustomTemplatesCustomTemplateDeleteIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. Template identifier`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault int64

	_ = cmd.PersistentFlags().Int64(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationCustomTemplatesCustomTemplateDeleteIDFlag(m *custom_templates.CustomTemplateDeleteParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetInt64(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationCustomTemplatesCustomTemplateDeleteResult parses request result and return the string content
func parseOperationCustomTemplatesCustomTemplateDeleteResult(resp0 *custom_templates.CustomTemplateDeleteNoContent, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning customTemplateDeleteNoContent is not supported

		// Non schema case: warning customTemplateDeleteBadRequest is not supported

		// Non schema case: warning customTemplateDeleteForbidden is not supported

		// Non schema case: warning customTemplateDeleteNotFound is not supported

		// Non schema case: warning customTemplateDeleteInternalServerError is not supported

		return "", respErr
	}

	// warning: non schema response customTemplateDeleteNoContent is not supported by go-swagger cli yet.

	return "", nil
}
