// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/portainer/client-api-go/v2/client/edge_update_schedules"

	"github.com/spf13/cobra"
)

// makeOperationEdgeUpdateSchedulesEdgeUpdateScheduleDeleteCmd returns a cmd to handle operation edgeUpdateScheduleDelete
func makeOperationEdgeUpdateSchedulesEdgeUpdateScheduleDeleteCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "EdgeUpdateScheduleDelete",
		Short: `**Access policy**: administrator`,
		RunE:  runOperationEdgeUpdateSchedulesEdgeUpdateScheduleDelete,
	}

	if err := registerOperationEdgeUpdateSchedulesEdgeUpdateScheduleDeleteParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationEdgeUpdateSchedulesEdgeUpdateScheduleDelete uses cmd flags to call endpoint api
func runOperationEdgeUpdateSchedulesEdgeUpdateScheduleDelete(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := edge_update_schedules.NewEdgeUpdateScheduleDeleteParams()
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationEdgeUpdateSchedulesEdgeUpdateScheduleDeleteResult(appCli.EdgeUpdateSchedules.EdgeUpdateScheduleDelete(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationEdgeUpdateSchedulesEdgeUpdateScheduleDeleteParamFlags registers all flags needed to fill params
func registerOperationEdgeUpdateSchedulesEdgeUpdateScheduleDeleteParamFlags(cmd *cobra.Command) error {
	return nil
}

// parseOperationEdgeUpdateSchedulesEdgeUpdateScheduleDeleteResult parses request result and return the string content
func parseOperationEdgeUpdateSchedulesEdgeUpdateScheduleDeleteResult(resp0 *edge_update_schedules.EdgeUpdateScheduleDeleteNoContent, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning edgeUpdateScheduleDeleteNoContent is not supported

		// Non schema case: warning edgeUpdateScheduleDeleteInternalServerError is not supported

		return "", respErr
	}

	// warning: non schema response edgeUpdateScheduleDeleteNoContent is not supported by go-swagger cli yet.

	return "", nil
}
