// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/portainer/client-api-go/v2/client/endpoint_groups"

	"github.com/spf13/cobra"
)

// makeOperationEndpointGroupsEndpointGroupDeleteEndpointCmd returns a cmd to handle operation endpointGroupDeleteEndpoint
func makeOperationEndpointGroupsEndpointGroupDeleteEndpointCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "EndpointGroupDeleteEndpoint",
		Short: `**Access policy**: administrator`,
		RunE:  runOperationEndpointGroupsEndpointGroupDeleteEndpoint,
	}

	if err := registerOperationEndpointGroupsEndpointGroupDeleteEndpointParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationEndpointGroupsEndpointGroupDeleteEndpoint uses cmd flags to call endpoint api
func runOperationEndpointGroupsEndpointGroupDeleteEndpoint(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := endpoint_groups.NewEndpointGroupDeleteEndpointParams()
	if err, _ := retrieveOperationEndpointGroupsEndpointGroupDeleteEndpointEndpointIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationEndpointGroupsEndpointGroupDeleteEndpointIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationEndpointGroupsEndpointGroupDeleteEndpointResult(appCli.EndpointGroups.EndpointGroupDeleteEndpoint(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationEndpointGroupsEndpointGroupDeleteEndpointParamFlags registers all flags needed to fill params
func registerOperationEndpointGroupsEndpointGroupDeleteEndpointParamFlags(cmd *cobra.Command) error {
	if err := registerOperationEndpointGroupsEndpointGroupDeleteEndpointEndpointIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationEndpointGroupsEndpointGroupDeleteEndpointIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationEndpointGroupsEndpointGroupDeleteEndpointEndpointIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	endpointIdDescription := `Required. Environment(Endpoint) identifier`

	var endpointIdFlagName string
	if cmdPrefix == "" {
		endpointIdFlagName = "endpointId"
	} else {
		endpointIdFlagName = fmt.Sprintf("%v.endpointId", cmdPrefix)
	}

	var endpointIdFlagDefault int64

	_ = cmd.PersistentFlags().Int64(endpointIdFlagName, endpointIdFlagDefault, endpointIdDescription)

	return nil
}
func registerOperationEndpointGroupsEndpointGroupDeleteEndpointIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. EndpointGroup identifier`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault int64

	_ = cmd.PersistentFlags().Int64(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationEndpointGroupsEndpointGroupDeleteEndpointEndpointIDFlag(m *endpoint_groups.EndpointGroupDeleteEndpointParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("endpointId") {

		var endpointIdFlagName string
		if cmdPrefix == "" {
			endpointIdFlagName = "endpointId"
		} else {
			endpointIdFlagName = fmt.Sprintf("%v.endpointId", cmdPrefix)
		}

		endpointIdFlagValue, err := cmd.Flags().GetInt64(endpointIdFlagName)
		if err != nil {
			return err, false
		}
		m.EndpointID = endpointIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationEndpointGroupsEndpointGroupDeleteEndpointIDFlag(m *endpoint_groups.EndpointGroupDeleteEndpointParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetInt64(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationEndpointGroupsEndpointGroupDeleteEndpointResult parses request result and return the string content
func parseOperationEndpointGroupsEndpointGroupDeleteEndpointResult(resp0 *endpoint_groups.EndpointGroupDeleteEndpointNoContent, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning endpointGroupDeleteEndpointNoContent is not supported

		// Non schema case: warning endpointGroupDeleteEndpointBadRequest is not supported

		// Non schema case: warning endpointGroupDeleteEndpointNotFound is not supported

		// Non schema case: warning endpointGroupDeleteEndpointInternalServerError is not supported

		return "", respErr
	}

	// warning: non schema response endpointGroupDeleteEndpointNoContent is not supported by go-swagger cli yet.

	return "", nil
}
