// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/portainer/client-api-go/v2/models"
	"github.com/spf13/cobra"
)

// Schema cli for LicensesDeleteResponse

// register flags to command
func registerModelLicensesDeleteResponseFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerLicensesDeleteResponseFailedKeys(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerLicensesDeleteResponseFailedKeys(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: failedKeys map[string]string map type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelLicensesDeleteResponseFlags(depth int, m *models.LicensesDeleteResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, failedKeysAdded := retrieveLicensesDeleteResponseFailedKeysFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || failedKeysAdded

	return nil, retAdded
}

func retrieveLicensesDeleteResponseFailedKeysFlags(depth int, m *models.LicensesDeleteResponse, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	failedKeysFlagName := fmt.Sprintf("%v.failedKeys", cmdPrefix)
	if cmd.Flags().Changed(failedKeysFlagName) {
		// warning: failedKeys map type map[string]string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
