// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/portainer/client-api-go/v2/models"
	"github.com/spf13/cobra"
)

// Schema cli for PodsecurityPodSecurityVolumeTypes

// register flags to command
func registerModelPodsecurityPodSecurityVolumeTypesFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerPodsecurityPodSecurityVolumeTypesAllowedTypes(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerPodsecurityPodSecurityVolumeTypesEnabled(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerPodsecurityPodSecurityVolumeTypesAllowedTypes(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: allowedTypes []string array type is not supported by go-swagger cli yet

	return nil
}

func registerPodsecurityPodSecurityVolumeTypesEnabled(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	enabledDescription := ``

	var enabledFlagName string
	if cmdPrefix == "" {
		enabledFlagName = "enabled"
	} else {
		enabledFlagName = fmt.Sprintf("%v.enabled", cmdPrefix)
	}

	var enabledFlagDefault bool

	_ = cmd.PersistentFlags().Bool(enabledFlagName, enabledFlagDefault, enabledDescription)

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelPodsecurityPodSecurityVolumeTypesFlags(depth int, m *models.PodsecurityPodSecurityVolumeTypes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, allowedTypesAdded := retrievePodsecurityPodSecurityVolumeTypesAllowedTypesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || allowedTypesAdded

	err, enabledAdded := retrievePodsecurityPodSecurityVolumeTypesEnabledFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || enabledAdded

	return nil, retAdded
}

func retrievePodsecurityPodSecurityVolumeTypesAllowedTypesFlags(depth int, m *models.PodsecurityPodSecurityVolumeTypes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	allowedTypesFlagName := fmt.Sprintf("%v.allowedTypes", cmdPrefix)
	if cmd.Flags().Changed(allowedTypesFlagName) {
		// warning: allowedTypes array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrievePodsecurityPodSecurityVolumeTypesEnabledFlags(depth int, m *models.PodsecurityPodSecurityVolumeTypes, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	enabledFlagName := fmt.Sprintf("%v.enabled", cmdPrefix)
	if cmd.Flags().Changed(enabledFlagName) {

		var enabledFlagName string
		if cmdPrefix == "" {
			enabledFlagName = "enabled"
		} else {
			enabledFlagName = fmt.Sprintf("%v.enabled", cmdPrefix)
		}

		enabledFlagValue, err := cmd.Flags().GetBool(enabledFlagName)
		if err != nil {
			return err, false
		}
		m.Enabled = &enabledFlagValue

		retAdded = true
	}

	return nil, retAdded
}
