// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/portainer/client-api-go/v2/client/edge"

	"github.com/spf13/cobra"
)

// makeOperationEdgePostEndpointsIDEdgeTrustCmd returns a cmd to handle operation postEndpointsIdEdgeTrust
func makeOperationEdgePostEndpointsIDEdgeTrustCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PostEndpointsIDEdgeTrust",
		Short: `**Access policy**: admin`,
		RunE:  runOperationEdgePostEndpointsIDEdgeTrust,
	}

	if err := registerOperationEdgePostEndpointsIDEdgeTrustParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationEdgePostEndpointsIDEdgeTrust uses cmd flags to call endpoint api
func runOperationEdgePostEndpointsIDEdgeTrust(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := edge.NewPostEndpointsIDEdgeTrustParams()
	if err, _ := retrieveOperationEdgePostEndpointsIDEdgeTrustIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationEdgePostEndpointsIDEdgeTrustResult(appCli.Edge.PostEndpointsIDEdgeTrust(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationEdgePostEndpointsIDEdgeTrustParamFlags registers all flags needed to fill params
func registerOperationEdgePostEndpointsIDEdgeTrustParamFlags(cmd *cobra.Command) error {
	if err := registerOperationEdgePostEndpointsIDEdgeTrustIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationEdgePostEndpointsIDEdgeTrustIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. Environment(Endpoint) Id`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationEdgePostEndpointsIDEdgeTrustIDFlag(m *edge.PostEndpointsIDEdgeTrustParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationEdgePostEndpointsIDEdgeTrustResult parses request result and return the string content
func parseOperationEdgePostEndpointsIDEdgeTrustResult(resp0 *edge.PostEndpointsIDEdgeTrustNoContent, respErr error) (string, error) {
	if respErr != nil {

		// Non schema case: warning postEndpointsIdEdgeTrustNoContent is not supported

		// Non schema case: warning postEndpointsIdEdgeTrustBadRequest is not supported

		// Non schema case: warning postEndpointsIdEdgeTrustInternalServerError is not supported

		return "", respErr
	}

	// warning: non schema response postEndpointsIdEdgeTrustNoContent is not supported by go-swagger cli yet.

	return "", nil
}
