// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/portainer/client-api-go/v2/client/users"
	"github.com/portainer/client-api-go/v2/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationUsersUserCreateGitCredentialCmd returns a cmd to handle operation userCreateGitCredential
func makeOperationUsersUserCreateGitCredentialCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "UserCreateGitCredential",
		Short: `Store a Git Credential for a user.
Only the calling user can store a git credential for themselves.
**Access policy**: restricted`,
		RunE: runOperationUsersUserCreateGitCredential,
	}

	if err := registerOperationUsersUserCreateGitCredentialParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationUsersUserCreateGitCredential uses cmd flags to call endpoint api
func runOperationUsersUserCreateGitCredential(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := users.NewUserCreateGitCredentialParams()
	if err, _ := retrieveOperationUsersUserCreateGitCredentialBodyFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationUsersUserCreateGitCredentialIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationUsersUserCreateGitCredentialResult(appCli.Users.UserCreateGitCredential(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationUsersUserCreateGitCredentialParamFlags registers all flags needed to fill params
func registerOperationUsersUserCreateGitCredentialParamFlags(cmd *cobra.Command) error {
	if err := registerOperationUsersUserCreateGitCredentialBodyParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationUsersUserCreateGitCredentialIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationUsersUserCreateGitCredentialBodyParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var bodyFlagName string
	if cmdPrefix == "" {
		bodyFlagName = "body"
	} else {
		bodyFlagName = fmt.Sprintf("%v.body", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(bodyFlagName, "", "Optional json string for [body]. details")

	// add flags for body
	if err := registerModelUsersUserGitCredentialCreatePayloadFlags(0, "usersUserGitCredentialCreatePayload", cmd); err != nil {
		return err
	}

	return nil
}
func registerOperationUsersUserCreateGitCredentialIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. User identifier`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault int64

	_ = cmd.PersistentFlags().Int64(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationUsersUserCreateGitCredentialBodyFlag(m *users.UserCreateGitCredentialParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("body") {
		// Read body string from cmd and unmarshal
		bodyValueStr, err := cmd.Flags().GetString("body")
		if err != nil {
			return err, false
		}

		bodyValue := models.UsersUserGitCredentialCreatePayload{}
		if err := json.Unmarshal([]byte(bodyValueStr), &bodyValue); err != nil {
			return fmt.Errorf("cannot unmarshal body string in models.UsersUserGitCredentialCreatePayload: %v", err), false
		}
		m.Body = &bodyValue
	}
	bodyValueModel := m.Body
	if swag.IsZero(bodyValueModel) {
		bodyValueModel = &models.UsersUserGitCredentialCreatePayload{}
	}
	err, added := retrieveModelUsersUserGitCredentialCreatePayloadFlags(0, bodyValueModel, "usersUserGitCredentialCreatePayload", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Body = bodyValueModel
	}
	if dryRun && debug {

		bodyValueDebugBytes, err := json.Marshal(m.Body)
		if err != nil {
			return err, false
		}
		logDebugf("Body dry-run payload: %v", string(bodyValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}
func retrieveOperationUsersUserCreateGitCredentialIDFlag(m *users.UserCreateGitCredentialParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetInt64(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationUsersUserCreateGitCredentialResult parses request result and return the string content
func parseOperationUsersUserCreateGitCredentialResult(resp0 *users.UserCreateGitCredentialCreated, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*users.UserCreateGitCredentialCreated)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning userCreateGitCredentialBadRequest is not supported

		// Non schema case: warning userCreateGitCredentialUnauthorized is not supported

		// Non schema case: warning userCreateGitCredentialForbidden is not supported

		// Non schema case: warning userCreateGitCredentialInternalServerError is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
