// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/portainer/client-api-go/v2/client/users"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationUsersUserGetGitCredentialCmd returns a cmd to handle operation userGetGitCredential
func makeOperationUsersUserGetGitCredentialCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use: "UserGetGitCredential",
		Short: `Gets the specific saved git credential for a user.
Only the calling user can retrieve git credential
**Access policy**: authenticated`,
		RunE: runOperationUsersUserGetGitCredential,
	}

	if err := registerOperationUsersUserGetGitCredentialParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationUsersUserGetGitCredential uses cmd flags to call endpoint api
func runOperationUsersUserGetGitCredential(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := users.NewUserGetGitCredentialParams()
	if err, _ := retrieveOperationUsersUserGetGitCredentialCredentialIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationUsersUserGetGitCredentialIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationUsersUserGetGitCredentialResult(appCli.Users.UserGetGitCredential(params, nil))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationUsersUserGetGitCredentialParamFlags registers all flags needed to fill params
func registerOperationUsersUserGetGitCredentialParamFlags(cmd *cobra.Command) error {
	if err := registerOperationUsersUserGetGitCredentialCredentialIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationUsersUserGetGitCredentialIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationUsersUserGetGitCredentialCredentialIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	credentialIdDescription := `Required. Git Credential identifier`

	var credentialIdFlagName string
	if cmdPrefix == "" {
		credentialIdFlagName = "credentialID"
	} else {
		credentialIdFlagName = fmt.Sprintf("%v.credentialID", cmdPrefix)
	}

	var credentialIdFlagDefault int64

	_ = cmd.PersistentFlags().Int64(credentialIdFlagName, credentialIdFlagDefault, credentialIdDescription)

	return nil
}
func registerOperationUsersUserGetGitCredentialIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. User identifier`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault int64

	_ = cmd.PersistentFlags().Int64(idFlagName, idFlagDefault, idDescription)

	return nil
}

func retrieveOperationUsersUserGetGitCredentialCredentialIDFlag(m *users.UserGetGitCredentialParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("credentialID") {

		var credentialIdFlagName string
		if cmdPrefix == "" {
			credentialIdFlagName = "credentialID"
		} else {
			credentialIdFlagName = fmt.Sprintf("%v.credentialID", cmdPrefix)
		}

		credentialIdFlagValue, err := cmd.Flags().GetInt64(credentialIdFlagName)
		if err != nil {
			return err, false
		}
		m.CredentialID = credentialIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationUsersUserGetGitCredentialIDFlag(m *users.UserGetGitCredentialParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetInt64(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}

// parseOperationUsersUserGetGitCredentialResult parses request result and return the string content
func parseOperationUsersUserGetGitCredentialResult(resp0 *users.UserGetGitCredentialOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*users.UserGetGitCredentialOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning userGetGitCredentialBadRequest is not supported

		// Non schema case: warning userGetGitCredentialForbidden is not supported

		// Non schema case: warning userGetGitCredentialNotFound is not supported

		// Non schema case: warning userGetGitCredentialInternalServerError is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
