// Code generated by go-swagger; DO NOT EDIT.

package edge_jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetEdgeJobsIDTasksParams creates a new GetEdgeJobsIDTasksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEdgeJobsIDTasksParams() *GetEdgeJobsIDTasksParams {
	return &GetEdgeJobsIDTasksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEdgeJobsIDTasksParamsWithTimeout creates a new GetEdgeJobsIDTasksParams object
// with the ability to set a timeout on a request.
func NewGetEdgeJobsIDTasksParamsWithTimeout(timeout time.Duration) *GetEdgeJobsIDTasksParams {
	return &GetEdgeJobsIDTasksParams{
		timeout: timeout,
	}
}

// NewGetEdgeJobsIDTasksParamsWithContext creates a new GetEdgeJobsIDTasksParams object
// with the ability to set a context for a request.
func NewGetEdgeJobsIDTasksParamsWithContext(ctx context.Context) *GetEdgeJobsIDTasksParams {
	return &GetEdgeJobsIDTasksParams{
		Context: ctx,
	}
}

// NewGetEdgeJobsIDTasksParamsWithHTTPClient creates a new GetEdgeJobsIDTasksParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEdgeJobsIDTasksParamsWithHTTPClient(client *http.Client) *GetEdgeJobsIDTasksParams {
	return &GetEdgeJobsIDTasksParams{
		HTTPClient: client,
	}
}

/* GetEdgeJobsIDTasksParams contains all the parameters to send to the API endpoint
   for the get edge jobs ID tasks operation.

   Typically these are written to a http.Request.
*/
type GetEdgeJobsIDTasksParams struct {

	/* ID.

	   EdgeJob Id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get edge jobs ID tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEdgeJobsIDTasksParams) WithDefaults() *GetEdgeJobsIDTasksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get edge jobs ID tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEdgeJobsIDTasksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get edge jobs ID tasks params
func (o *GetEdgeJobsIDTasksParams) WithTimeout(timeout time.Duration) *GetEdgeJobsIDTasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get edge jobs ID tasks params
func (o *GetEdgeJobsIDTasksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get edge jobs ID tasks params
func (o *GetEdgeJobsIDTasksParams) WithContext(ctx context.Context) *GetEdgeJobsIDTasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get edge jobs ID tasks params
func (o *GetEdgeJobsIDTasksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get edge jobs ID tasks params
func (o *GetEdgeJobsIDTasksParams) WithHTTPClient(client *http.Client) *GetEdgeJobsIDTasksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get edge jobs ID tasks params
func (o *GetEdgeJobsIDTasksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get edge jobs ID tasks params
func (o *GetEdgeJobsIDTasksParams) WithID(id string) *GetEdgeJobsIDTasksParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get edge jobs ID tasks params
func (o *GetEdgeJobsIDTasksParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetEdgeJobsIDTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
