// Code generated by go-swagger; DO NOT EDIT.

package models_ee

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RegistriesDeleteTagsPayload registries delete tags payload
//
// swagger:model registries.deleteTagsPayload
type RegistriesDeleteTagsPayload struct {

	// tags
	Tags []string `json:"tags"`
}

// Validate validates this registries delete tags payload
func (m *RegistriesDeleteTagsPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this registries delete tags payload based on context it is used
func (m *RegistriesDeleteTagsPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegistriesDeleteTagsPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegistriesDeleteTagsPayload) UnmarshalBinary(b []byte) error {
	var res RegistriesDeleteTagsPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
