// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChatChatQueryResponse chat chat query response
//
// swagger:model chat.chatQueryResponse
type ChatChatQueryResponse struct {

	// Message is the message that is returned by the OpenAI API.
	Message string `json:"message,omitempty"`

	// Yaml is the content of the compose / kubernetes manifest file that was generated by the OpenAI API as part of the response.
	Yaml string `json:"yaml,omitempty"`
}

// Validate validates this chat chat query response
func (m *ChatChatQueryResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this chat chat query response based on context it is used
func (m *ChatChatQueryResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChatChatQueryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChatChatQueryResponse) UnmarshalBinary(b []byte) error {
	var res ChatChatQueryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
