// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EdgejobsTaskContainer edgejobs task container
//
// swagger:model edgejobs.taskContainer
type EdgejobsTaskContainer struct {

	// endpoint Id
	EndpointID int64 `json:"EndpointId,omitempty"`

	// Id
	ID string `json:"Id,omitempty"`

	// logs status
	LogsStatus int64 `json:"LogsStatus,omitempty"`
}

// Validate validates this edgejobs task container
func (m *EdgejobsTaskContainer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this edgejobs task container based on context it is used
func (m *EdgejobsTaskContainer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EdgejobsTaskContainer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EdgejobsTaskContainer) UnmarshalBinary(b []byte) error {
	var res EdgejobsTaskContainer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
