// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// KubernetesK8sCronJobDeleteRequests kubernetes k8s cron job delete requests
//
// swagger:model kubernetes.K8sCronJobDeleteRequests
type KubernetesK8sCronJobDeleteRequests map[string][]string

// Validate validates this kubernetes k8s cron job delete requests
func (m KubernetesK8sCronJobDeleteRequests) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kubernetes k8s cron job delete requests based on context it is used
func (m KubernetesK8sCronJobDeleteRequests) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
