// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReleaseReleaseElement release release element
//
// swagger:model release.ReleaseElement
type ReleaseReleaseElement struct {

	// app version
	AppVersion string `json:"appVersion,omitempty"`

	// chart
	Chart string `json:"chart,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// revision
	Revision string `json:"revision,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// updated
	Updated string `json:"updated,omitempty"`
}

// Validate validates this release release element
func (m *ReleaseReleaseElement) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this release release element based on context it is used
func (m *ReleaseReleaseElement) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReleaseReleaseElement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReleaseReleaseElement) UnmarshalBinary(b []byte) error {
	var res ReleaseReleaseElement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
