// Code generated by go-swagger; DO NOT EDIT.

package stacks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// WebhookInvokeReader is a Reader for the WebhookInvoke structure.
type WebhookInvokeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WebhookInvokeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWebhookInvokeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewWebhookInvokeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewWebhookInvokeConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewWebhookInvokeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewWebhookInvokeOK creates a WebhookInvokeOK with default headers values
func NewWebhookInvokeOK() *WebhookInvokeOK {
	return &WebhookInvokeOK{}
}

/*
WebhookInvokeOK describes a response with status code 200, with default header values.

Success
*/
type WebhookInvokeOK struct {
}

// IsSuccess returns true when this webhook invoke o k response has a 2xx status code
func (o *WebhookInvokeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this webhook invoke o k response has a 3xx status code
func (o *WebhookInvokeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this webhook invoke o k response has a 4xx status code
func (o *WebhookInvokeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this webhook invoke o k response has a 5xx status code
func (o *WebhookInvokeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this webhook invoke o k response a status code equal to that given
func (o *WebhookInvokeOK) IsCode(code int) bool {
	return code == 200
}

func (o *WebhookInvokeOK) Error() string {
	return fmt.Sprintf("[POST /stacks/webhooks/{webhookID}][%d] webhookInvokeOK ", 200)
}

func (o *WebhookInvokeOK) String() string {
	return fmt.Sprintf("[POST /stacks/webhooks/{webhookID}][%d] webhookInvokeOK ", 200)
}

func (o *WebhookInvokeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWebhookInvokeBadRequest creates a WebhookInvokeBadRequest with default headers values
func NewWebhookInvokeBadRequest() *WebhookInvokeBadRequest {
	return &WebhookInvokeBadRequest{}
}

/*
WebhookInvokeBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type WebhookInvokeBadRequest struct {
}

// IsSuccess returns true when this webhook invoke bad request response has a 2xx status code
func (o *WebhookInvokeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this webhook invoke bad request response has a 3xx status code
func (o *WebhookInvokeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this webhook invoke bad request response has a 4xx status code
func (o *WebhookInvokeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this webhook invoke bad request response has a 5xx status code
func (o *WebhookInvokeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this webhook invoke bad request response a status code equal to that given
func (o *WebhookInvokeBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *WebhookInvokeBadRequest) Error() string {
	return fmt.Sprintf("[POST /stacks/webhooks/{webhookID}][%d] webhookInvokeBadRequest ", 400)
}

func (o *WebhookInvokeBadRequest) String() string {
	return fmt.Sprintf("[POST /stacks/webhooks/{webhookID}][%d] webhookInvokeBadRequest ", 400)
}

func (o *WebhookInvokeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWebhookInvokeConflict creates a WebhookInvokeConflict with default headers values
func NewWebhookInvokeConflict() *WebhookInvokeConflict {
	return &WebhookInvokeConflict{}
}

/*
WebhookInvokeConflict describes a response with status code 409, with default header values.

Conflict
*/
type WebhookInvokeConflict struct {
}

// IsSuccess returns true when this webhook invoke conflict response has a 2xx status code
func (o *WebhookInvokeConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this webhook invoke conflict response has a 3xx status code
func (o *WebhookInvokeConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this webhook invoke conflict response has a 4xx status code
func (o *WebhookInvokeConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this webhook invoke conflict response has a 5xx status code
func (o *WebhookInvokeConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this webhook invoke conflict response a status code equal to that given
func (o *WebhookInvokeConflict) IsCode(code int) bool {
	return code == 409
}

func (o *WebhookInvokeConflict) Error() string {
	return fmt.Sprintf("[POST /stacks/webhooks/{webhookID}][%d] webhookInvokeConflict ", 409)
}

func (o *WebhookInvokeConflict) String() string {
	return fmt.Sprintf("[POST /stacks/webhooks/{webhookID}][%d] webhookInvokeConflict ", 409)
}

func (o *WebhookInvokeConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewWebhookInvokeInternalServerError creates a WebhookInvokeInternalServerError with default headers values
func NewWebhookInvokeInternalServerError() *WebhookInvokeInternalServerError {
	return &WebhookInvokeInternalServerError{}
}

/*
WebhookInvokeInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type WebhookInvokeInternalServerError struct {
}

// IsSuccess returns true when this webhook invoke internal server error response has a 2xx status code
func (o *WebhookInvokeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this webhook invoke internal server error response has a 3xx status code
func (o *WebhookInvokeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this webhook invoke internal server error response has a 4xx status code
func (o *WebhookInvokeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this webhook invoke internal server error response has a 5xx status code
func (o *WebhookInvokeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this webhook invoke internal server error response a status code equal to that given
func (o *WebhookInvokeInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *WebhookInvokeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /stacks/webhooks/{webhookID}][%d] webhookInvokeInternalServerError ", 500)
}

func (o *WebhookInvokeInternalServerError) String() string {
	return fmt.Sprintf("[POST /stacks/webhooks/{webhookID}][%d] webhookInvokeInternalServerError ", 500)
}

func (o *WebhookInvokeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
