// Code generated by go-swagger; DO NOT EDIT.

package registries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RegistryConfigureReader is a Reader for the RegistryConfigure structure.
type RegistryConfigureReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RegistryConfigureReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRegistryConfigureNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRegistryConfigureBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRegistryConfigureForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRegistryConfigureNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRegistryConfigureInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRegistryConfigureNoContent creates a RegistryConfigureNoContent with default headers values
func NewRegistryConfigureNoContent() *RegistryConfigureNoContent {
	return &RegistryConfigureNoContent{}
}

/* RegistryConfigureNoContent describes a response with status code 204, with default header values.

Success
*/
type RegistryConfigureNoContent struct {
}

func (o *RegistryConfigureNoContent) Error() string {
	return fmt.Sprintf("[POST /registries/{id}/configure][%d] registryConfigureNoContent ", 204)
}

func (o *RegistryConfigureNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRegistryConfigureBadRequest creates a RegistryConfigureBadRequest with default headers values
func NewRegistryConfigureBadRequest() *RegistryConfigureBadRequest {
	return &RegistryConfigureBadRequest{}
}

/* RegistryConfigureBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type RegistryConfigureBadRequest struct {
}

func (o *RegistryConfigureBadRequest) Error() string {
	return fmt.Sprintf("[POST /registries/{id}/configure][%d] registryConfigureBadRequest ", 400)
}

func (o *RegistryConfigureBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRegistryConfigureForbidden creates a RegistryConfigureForbidden with default headers values
func NewRegistryConfigureForbidden() *RegistryConfigureForbidden {
	return &RegistryConfigureForbidden{}
}

/* RegistryConfigureForbidden describes a response with status code 403, with default header values.

Permission denied
*/
type RegistryConfigureForbidden struct {
}

func (o *RegistryConfigureForbidden) Error() string {
	return fmt.Sprintf("[POST /registries/{id}/configure][%d] registryConfigureForbidden ", 403)
}

func (o *RegistryConfigureForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRegistryConfigureNotFound creates a RegistryConfigureNotFound with default headers values
func NewRegistryConfigureNotFound() *RegistryConfigureNotFound {
	return &RegistryConfigureNotFound{}
}

/* RegistryConfigureNotFound describes a response with status code 404, with default header values.

Registry not found
*/
type RegistryConfigureNotFound struct {
}

func (o *RegistryConfigureNotFound) Error() string {
	return fmt.Sprintf("[POST /registries/{id}/configure][%d] registryConfigureNotFound ", 404)
}

func (o *RegistryConfigureNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRegistryConfigureInternalServerError creates a RegistryConfigureInternalServerError with default headers values
func NewRegistryConfigureInternalServerError() *RegistryConfigureInternalServerError {
	return &RegistryConfigureInternalServerError{}
}

/* RegistryConfigureInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type RegistryConfigureInternalServerError struct {
}

func (o *RegistryConfigureInternalServerError) Error() string {
	return fmt.Sprintf("[POST /registries/{id}/configure][%d] registryConfigureInternalServerError ", 500)
}

func (o *RegistryConfigureInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
