// Code generated by go-swagger; DO NOT EDIT.

package endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewEndpointMTLSCertificateParams creates a new EndpointMTLSCertificateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEndpointMTLSCertificateParams() *EndpointMTLSCertificateParams {
	return &EndpointMTLSCertificateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEndpointMTLSCertificateParamsWithTimeout creates a new EndpointMTLSCertificateParams object
// with the ability to set a timeout on a request.
func NewEndpointMTLSCertificateParamsWithTimeout(timeout time.Duration) *EndpointMTLSCertificateParams {
	return &EndpointMTLSCertificateParams{
		timeout: timeout,
	}
}

// NewEndpointMTLSCertificateParamsWithContext creates a new EndpointMTLSCertificateParams object
// with the ability to set a context for a request.
func NewEndpointMTLSCertificateParamsWithContext(ctx context.Context) *EndpointMTLSCertificateParams {
	return &EndpointMTLSCertificateParams{
		Context: ctx,
	}
}

// NewEndpointMTLSCertificateParamsWithHTTPClient creates a new EndpointMTLSCertificateParams object
// with the ability to set a custom HTTPClient for a request.
func NewEndpointMTLSCertificateParamsWithHTTPClient(client *http.Client) *EndpointMTLSCertificateParams {
	return &EndpointMTLSCertificateParams{
		HTTPClient: client,
	}
}

/*
EndpointMTLSCertificateParams contains all the parameters to send to the API endpoint

	for the endpoint m TLS certificate operation.

	Typically these are written to a http.Request.
*/
type EndpointMTLSCertificateParams struct {

	/* ID.

	   Environment(Endpoint) identifier
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the endpoint m TLS certificate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EndpointMTLSCertificateParams) WithDefaults() *EndpointMTLSCertificateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the endpoint m TLS certificate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EndpointMTLSCertificateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the endpoint m TLS certificate params
func (o *EndpointMTLSCertificateParams) WithTimeout(timeout time.Duration) *EndpointMTLSCertificateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the endpoint m TLS certificate params
func (o *EndpointMTLSCertificateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the endpoint m TLS certificate params
func (o *EndpointMTLSCertificateParams) WithContext(ctx context.Context) *EndpointMTLSCertificateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the endpoint m TLS certificate params
func (o *EndpointMTLSCertificateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the endpoint m TLS certificate params
func (o *EndpointMTLSCertificateParams) WithHTTPClient(client *http.Client) *EndpointMTLSCertificateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the endpoint m TLS certificate params
func (o *EndpointMTLSCertificateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the endpoint m TLS certificate params
func (o *EndpointMTLSCertificateParams) WithID(id int64) *EndpointMTLSCertificateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the endpoint m TLS certificate params
func (o *EndpointMTLSCertificateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *EndpointMTLSCertificateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
