// Code generated by go-swagger; DO NOT EDIT.

package nomad

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTaskLogsParams creates a new GetTaskLogsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTaskLogsParams() *GetTaskLogsParams {
	return &GetTaskLogsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTaskLogsParamsWithTimeout creates a new GetTaskLogsParams object
// with the ability to set a timeout on a request.
func NewGetTaskLogsParamsWithTimeout(timeout time.Duration) *GetTaskLogsParams {
	return &GetTaskLogsParams{
		timeout: timeout,
	}
}

// NewGetTaskLogsParamsWithContext creates a new GetTaskLogsParams object
// with the ability to set a context for a request.
func NewGetTaskLogsParamsWithContext(ctx context.Context) *GetTaskLogsParams {
	return &GetTaskLogsParams{
		Context: ctx,
	}
}

// NewGetTaskLogsParamsWithHTTPClient creates a new GetTaskLogsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTaskLogsParamsWithHTTPClient(client *http.Client) *GetTaskLogsParams {
	return &GetTaskLogsParams{
		HTTPClient: client,
	}
}

/*
GetTaskLogsParams contains all the parameters to send to the API endpoint

	for the get task logs operation.

	Typically these are written to a http.Request.
*/
type GetTaskLogsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get task logs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTaskLogsParams) WithDefaults() *GetTaskLogsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get task logs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTaskLogsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get task logs params
func (o *GetTaskLogsParams) WithTimeout(timeout time.Duration) *GetTaskLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get task logs params
func (o *GetTaskLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get task logs params
func (o *GetTaskLogsParams) WithContext(ctx context.Context) *GetTaskLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get task logs params
func (o *GetTaskLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get task logs params
func (o *GetTaskLogsParams) WithHTTPClient(client *http.Client) *GetTaskLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get task logs params
func (o *GetTaskLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTaskLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
