// Code generated by go-swagger; DO NOT EDIT.

package endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewEndpointCreateGlobalKeyParams creates a new EndpointCreateGlobalKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEndpointCreateGlobalKeyParams() *EndpointCreateGlobalKeyParams {
	return &EndpointCreateGlobalKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEndpointCreateGlobalKeyParamsWithTimeout creates a new EndpointCreateGlobalKeyParams object
// with the ability to set a timeout on a request.
func NewEndpointCreateGlobalKeyParamsWithTimeout(timeout time.Duration) *EndpointCreateGlobalKeyParams {
	return &EndpointCreateGlobalKeyParams{
		timeout: timeout,
	}
}

// NewEndpointCreateGlobalKeyParamsWithContext creates a new EndpointCreateGlobalKeyParams object
// with the ability to set a context for a request.
func NewEndpointCreateGlobalKeyParamsWithContext(ctx context.Context) *EndpointCreateGlobalKeyParams {
	return &EndpointCreateGlobalKeyParams{
		Context: ctx,
	}
}

// NewEndpointCreateGlobalKeyParamsWithHTTPClient creates a new EndpointCreateGlobalKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewEndpointCreateGlobalKeyParamsWithHTTPClient(client *http.Client) *EndpointCreateGlobalKeyParams {
	return &EndpointCreateGlobalKeyParams{
		HTTPClient: client,
	}
}

/*
EndpointCreateGlobalKeyParams contains all the parameters to send to the API endpoint

	for the endpoint create global key operation.

	Typically these are written to a http.Request.
*/
type EndpointCreateGlobalKeyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the endpoint create global key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EndpointCreateGlobalKeyParams) WithDefaults() *EndpointCreateGlobalKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the endpoint create global key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EndpointCreateGlobalKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the endpoint create global key params
func (o *EndpointCreateGlobalKeyParams) WithTimeout(timeout time.Duration) *EndpointCreateGlobalKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the endpoint create global key params
func (o *EndpointCreateGlobalKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the endpoint create global key params
func (o *EndpointCreateGlobalKeyParams) WithContext(ctx context.Context) *EndpointCreateGlobalKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the endpoint create global key params
func (o *EndpointCreateGlobalKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the endpoint create global key params
func (o *EndpointCreateGlobalKeyParams) WithHTTPClient(client *http.Client) *EndpointCreateGlobalKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the endpoint create global key params
func (o *EndpointCreateGlobalKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *EndpointCreateGlobalKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
