// Code generated by go-swagger; DO NOT EDIT.

package endpoint_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// EndpointGroupDeleteReader is a Reader for the EndpointGroupDelete structure.
type EndpointGroupDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndpointGroupDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewEndpointGroupDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEndpointGroupDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEndpointGroupDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEndpointGroupDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEndpointGroupDeleteNoContent creates a EndpointGroupDeleteNoContent with default headers values
func NewEndpointGroupDeleteNoContent() *EndpointGroupDeleteNoContent {
	return &EndpointGroupDeleteNoContent{}
}

/* EndpointGroupDeleteNoContent describes a response with status code 204, with default header values.

Success
*/
type EndpointGroupDeleteNoContent struct {
}

func (o *EndpointGroupDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /endpoint_groups/{id}][%d] endpointGroupDeleteNoContent ", 204)
}

func (o *EndpointGroupDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndpointGroupDeleteBadRequest creates a EndpointGroupDeleteBadRequest with default headers values
func NewEndpointGroupDeleteBadRequest() *EndpointGroupDeleteBadRequest {
	return &EndpointGroupDeleteBadRequest{}
}

/* EndpointGroupDeleteBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type EndpointGroupDeleteBadRequest struct {
}

func (o *EndpointGroupDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /endpoint_groups/{id}][%d] endpointGroupDeleteBadRequest ", 400)
}

func (o *EndpointGroupDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndpointGroupDeleteNotFound creates a EndpointGroupDeleteNotFound with default headers values
func NewEndpointGroupDeleteNotFound() *EndpointGroupDeleteNotFound {
	return &EndpointGroupDeleteNotFound{}
}

/* EndpointGroupDeleteNotFound describes a response with status code 404, with default header values.

EndpointGroup not found
*/
type EndpointGroupDeleteNotFound struct {
}

func (o *EndpointGroupDeleteNotFound) Error() string {
	return fmt.Sprintf("[DELETE /endpoint_groups/{id}][%d] endpointGroupDeleteNotFound ", 404)
}

func (o *EndpointGroupDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndpointGroupDeleteInternalServerError creates a EndpointGroupDeleteInternalServerError with default headers values
func NewEndpointGroupDeleteInternalServerError() *EndpointGroupDeleteInternalServerError {
	return &EndpointGroupDeleteInternalServerError{}
}

/* EndpointGroupDeleteInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type EndpointGroupDeleteInternalServerError struct {
}

func (o *EndpointGroupDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /endpoint_groups/{id}][%d] endpointGroupDeleteInternalServerError ", 500)
}

func (o *EndpointGroupDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
