// Code generated by go-swagger; DO NOT EDIT.

package kubernetes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/portainer/client-api-go/v2/pkg/models"
)

// NewCreateKubernetesNamespaceParams creates a new CreateKubernetesNamespaceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateKubernetesNamespaceParams() *CreateKubernetesNamespaceParams {
	return &CreateKubernetesNamespaceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateKubernetesNamespaceParamsWithTimeout creates a new CreateKubernetesNamespaceParams object
// with the ability to set a timeout on a request.
func NewCreateKubernetesNamespaceParamsWithTimeout(timeout time.Duration) *CreateKubernetesNamespaceParams {
	return &CreateKubernetesNamespaceParams{
		timeout: timeout,
	}
}

// NewCreateKubernetesNamespaceParamsWithContext creates a new CreateKubernetesNamespaceParams object
// with the ability to set a context for a request.
func NewCreateKubernetesNamespaceParamsWithContext(ctx context.Context) *CreateKubernetesNamespaceParams {
	return &CreateKubernetesNamespaceParams{
		Context: ctx,
	}
}

// NewCreateKubernetesNamespaceParamsWithHTTPClient creates a new CreateKubernetesNamespaceParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateKubernetesNamespaceParamsWithHTTPClient(client *http.Client) *CreateKubernetesNamespaceParams {
	return &CreateKubernetesNamespaceParams{
		HTTPClient: client,
	}
}

/*
CreateKubernetesNamespaceParams contains all the parameters to send to the API endpoint

	for the create kubernetes namespace operation.

	Typically these are written to a http.Request.
*/
type CreateKubernetesNamespaceParams struct {

	/* Body.

	   Namespace configuration details
	*/
	Body *models.ModelsK8sNamespaceDetails

	/* ID.

	   Environment identifier
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create kubernetes namespace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateKubernetesNamespaceParams) WithDefaults() *CreateKubernetesNamespaceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create kubernetes namespace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateKubernetesNamespaceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create kubernetes namespace params
func (o *CreateKubernetesNamespaceParams) WithTimeout(timeout time.Duration) *CreateKubernetesNamespaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create kubernetes namespace params
func (o *CreateKubernetesNamespaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create kubernetes namespace params
func (o *CreateKubernetesNamespaceParams) WithContext(ctx context.Context) *CreateKubernetesNamespaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create kubernetes namespace params
func (o *CreateKubernetesNamespaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create kubernetes namespace params
func (o *CreateKubernetesNamespaceParams) WithHTTPClient(client *http.Client) *CreateKubernetesNamespaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create kubernetes namespace params
func (o *CreateKubernetesNamespaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create kubernetes namespace params
func (o *CreateKubernetesNamespaceParams) WithBody(body *models.ModelsK8sNamespaceDetails) *CreateKubernetesNamespaceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create kubernetes namespace params
func (o *CreateKubernetesNamespaceParams) SetBody(body *models.ModelsK8sNamespaceDetails) {
	o.Body = body
}

// WithID adds the id to the create kubernetes namespace params
func (o *CreateKubernetesNamespaceParams) WithID(id int64) *CreateKubernetesNamespaceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create kubernetes namespace params
func (o *CreateKubernetesNamespaceParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreateKubernetesNamespaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
