// Code generated by go-swagger; DO NOT EDIT.

package kubernetes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteClusterRolesParams creates a new DeleteClusterRolesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteClusterRolesParams() *DeleteClusterRolesParams {
	return &DeleteClusterRolesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteClusterRolesParamsWithTimeout creates a new DeleteClusterRolesParams object
// with the ability to set a timeout on a request.
func NewDeleteClusterRolesParamsWithTimeout(timeout time.Duration) *DeleteClusterRolesParams {
	return &DeleteClusterRolesParams{
		timeout: timeout,
	}
}

// NewDeleteClusterRolesParamsWithContext creates a new DeleteClusterRolesParams object
// with the ability to set a context for a request.
func NewDeleteClusterRolesParamsWithContext(ctx context.Context) *DeleteClusterRolesParams {
	return &DeleteClusterRolesParams{
		Context: ctx,
	}
}

// NewDeleteClusterRolesParamsWithHTTPClient creates a new DeleteClusterRolesParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteClusterRolesParamsWithHTTPClient(client *http.Client) *DeleteClusterRolesParams {
	return &DeleteClusterRolesParams{
		HTTPClient: client,
	}
}

/*
DeleteClusterRolesParams contains all the parameters to send to the API endpoint

	for the delete cluster roles operation.

	Typically these are written to a http.Request.
*/
type DeleteClusterRolesParams struct {

	/* ID.

	   Environment identifier
	*/
	ID int64

	/* Payload.

	   A list of cluster roles to delete
	*/
	Payload []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete cluster roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteClusterRolesParams) WithDefaults() *DeleteClusterRolesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete cluster roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteClusterRolesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete cluster roles params
func (o *DeleteClusterRolesParams) WithTimeout(timeout time.Duration) *DeleteClusterRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete cluster roles params
func (o *DeleteClusterRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete cluster roles params
func (o *DeleteClusterRolesParams) WithContext(ctx context.Context) *DeleteClusterRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete cluster roles params
func (o *DeleteClusterRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete cluster roles params
func (o *DeleteClusterRolesParams) WithHTTPClient(client *http.Client) *DeleteClusterRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete cluster roles params
func (o *DeleteClusterRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete cluster roles params
func (o *DeleteClusterRolesParams) WithID(id int64) *DeleteClusterRolesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete cluster roles params
func (o *DeleteClusterRolesParams) SetID(id int64) {
	o.ID = id
}

// WithPayload adds the payload to the delete cluster roles params
func (o *DeleteClusterRolesParams) WithPayload(payload []string) *DeleteClusterRolesParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the delete cluster roles params
func (o *DeleteClusterRolesParams) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteClusterRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}
	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
