// Code generated by go-swagger; DO NOT EDIT.

package edge_update_schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/portainer/client-api-go/ee/v2/models"
)

// NewEdgeUpdateScheduleActiveSchedulesListParams creates a new EdgeUpdateScheduleActiveSchedulesListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewEdgeUpdateScheduleActiveSchedulesListParams() *EdgeUpdateScheduleActiveSchedulesListParams {
	return &EdgeUpdateScheduleActiveSchedulesListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewEdgeUpdateScheduleActiveSchedulesListParamsWithTimeout creates a new EdgeUpdateScheduleActiveSchedulesListParams object
// with the ability to set a timeout on a request.
func NewEdgeUpdateScheduleActiveSchedulesListParamsWithTimeout(timeout time.Duration) *EdgeUpdateScheduleActiveSchedulesListParams {
	return &EdgeUpdateScheduleActiveSchedulesListParams{
		timeout: timeout,
	}
}

// NewEdgeUpdateScheduleActiveSchedulesListParamsWithContext creates a new EdgeUpdateScheduleActiveSchedulesListParams object
// with the ability to set a context for a request.
func NewEdgeUpdateScheduleActiveSchedulesListParamsWithContext(ctx context.Context) *EdgeUpdateScheduleActiveSchedulesListParams {
	return &EdgeUpdateScheduleActiveSchedulesListParams{
		Context: ctx,
	}
}

// NewEdgeUpdateScheduleActiveSchedulesListParamsWithHTTPClient creates a new EdgeUpdateScheduleActiveSchedulesListParams object
// with the ability to set a custom HTTPClient for a request.
func NewEdgeUpdateScheduleActiveSchedulesListParamsWithHTTPClient(client *http.Client) *EdgeUpdateScheduleActiveSchedulesListParams {
	return &EdgeUpdateScheduleActiveSchedulesListParams{
		HTTPClient: client,
	}
}

/*
EdgeUpdateScheduleActiveSchedulesListParams contains all the parameters to send to the API endpoint

	for the edge update schedule active schedules list operation.

	Typically these are written to a http.Request.
*/
type EdgeUpdateScheduleActiveSchedulesListParams struct {

	/* Body.

	   Active schedule query
	*/
	Body *models.EdgeupdateschedulesActiveSchedulePayload

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the edge update schedule active schedules list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EdgeUpdateScheduleActiveSchedulesListParams) WithDefaults() *EdgeUpdateScheduleActiveSchedulesListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the edge update schedule active schedules list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *EdgeUpdateScheduleActiveSchedulesListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the edge update schedule active schedules list params
func (o *EdgeUpdateScheduleActiveSchedulesListParams) WithTimeout(timeout time.Duration) *EdgeUpdateScheduleActiveSchedulesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the edge update schedule active schedules list params
func (o *EdgeUpdateScheduleActiveSchedulesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the edge update schedule active schedules list params
func (o *EdgeUpdateScheduleActiveSchedulesListParams) WithContext(ctx context.Context) *EdgeUpdateScheduleActiveSchedulesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the edge update schedule active schedules list params
func (o *EdgeUpdateScheduleActiveSchedulesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the edge update schedule active schedules list params
func (o *EdgeUpdateScheduleActiveSchedulesListParams) WithHTTPClient(client *http.Client) *EdgeUpdateScheduleActiveSchedulesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the edge update schedule active schedules list params
func (o *EdgeUpdateScheduleActiveSchedulesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the edge update schedule active schedules list params
func (o *EdgeUpdateScheduleActiveSchedulesListParams) WithBody(body *models.EdgeupdateschedulesActiveSchedulePayload) *EdgeUpdateScheduleActiveSchedulesListParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the edge update schedule active schedules list params
func (o *EdgeUpdateScheduleActiveSchedulesListParams) SetBody(body *models.EdgeupdateschedulesActiveSchedulePayload) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *EdgeUpdateScheduleActiveSchedulesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
