// Code generated by go-swagger; DO NOT EDIT.

package nomad

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLeaderParams creates a new GetLeaderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLeaderParams() *GetLeaderParams {
	return &GetLeaderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLeaderParamsWithTimeout creates a new GetLeaderParams object
// with the ability to set a timeout on a request.
func NewGetLeaderParamsWithTimeout(timeout time.Duration) *GetLeaderParams {
	return &GetLeaderParams{
		timeout: timeout,
	}
}

// NewGetLeaderParamsWithContext creates a new GetLeaderParams object
// with the ability to set a context for a request.
func NewGetLeaderParamsWithContext(ctx context.Context) *GetLeaderParams {
	return &GetLeaderParams{
		Context: ctx,
	}
}

// NewGetLeaderParamsWithHTTPClient creates a new GetLeaderParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLeaderParamsWithHTTPClient(client *http.Client) *GetLeaderParams {
	return &GetLeaderParams{
		HTTPClient: client,
	}
}

/*
GetLeaderParams contains all the parameters to send to the API endpoint

	for the get leader operation.

	Typically these are written to a http.Request.
*/
type GetLeaderParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get leader params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLeaderParams) WithDefaults() *GetLeaderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get leader params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLeaderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get leader params
func (o *GetLeaderParams) WithTimeout(timeout time.Duration) *GetLeaderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get leader params
func (o *GetLeaderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get leader params
func (o *GetLeaderParams) WithContext(ctx context.Context) *GetLeaderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get leader params
func (o *GetLeaderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get leader params
func (o *GetLeaderParams) WithHTTPClient(client *http.Client) *GetLeaderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get leader params
func (o *GetLeaderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLeaderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
