// Code generated by go-swagger; DO NOT EDIT.

package settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SettingsLDAPCheckReader is a Reader for the SettingsLDAPCheck structure.
type SettingsLDAPCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SettingsLDAPCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewSettingsLDAPCheckNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSettingsLDAPCheckBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSettingsLDAPCheckInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSettingsLDAPCheckNoContent creates a SettingsLDAPCheckNoContent with default headers values
func NewSettingsLDAPCheckNoContent() *SettingsLDAPCheckNoContent {
	return &SettingsLDAPCheckNoContent{}
}

/* SettingsLDAPCheckNoContent describes a response with status code 204, with default header values.

Success
*/
type SettingsLDAPCheckNoContent struct {
}

func (o *SettingsLDAPCheckNoContent) Error() string {
	return fmt.Sprintf("[PUT /settings/ldap/check][%d] settingsLDAPCheckNoContent ", 204)
}

func (o *SettingsLDAPCheckNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSettingsLDAPCheckBadRequest creates a SettingsLDAPCheckBadRequest with default headers values
func NewSettingsLDAPCheckBadRequest() *SettingsLDAPCheckBadRequest {
	return &SettingsLDAPCheckBadRequest{}
}

/* SettingsLDAPCheckBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type SettingsLDAPCheckBadRequest struct {
}

func (o *SettingsLDAPCheckBadRequest) Error() string {
	return fmt.Sprintf("[PUT /settings/ldap/check][%d] settingsLDAPCheckBadRequest ", 400)
}

func (o *SettingsLDAPCheckBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSettingsLDAPCheckInternalServerError creates a SettingsLDAPCheckInternalServerError with default headers values
func NewSettingsLDAPCheckInternalServerError() *SettingsLDAPCheckInternalServerError {
	return &SettingsLDAPCheckInternalServerError{}
}

/* SettingsLDAPCheckInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type SettingsLDAPCheckInternalServerError struct {
}

func (o *SettingsLDAPCheckInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /settings/ldap/check][%d] settingsLDAPCheckInternalServerError ", 500)
}

func (o *SettingsLDAPCheckInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
