// Code generated by go-swagger; DO NOT EDIT.

package custom_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCustomTemplateInspectParams creates a new CustomTemplateInspectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomTemplateInspectParams() *CustomTemplateInspectParams {
	return &CustomTemplateInspectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCustomTemplateInspectParamsWithTimeout creates a new CustomTemplateInspectParams object
// with the ability to set a timeout on a request.
func NewCustomTemplateInspectParamsWithTimeout(timeout time.Duration) *CustomTemplateInspectParams {
	return &CustomTemplateInspectParams{
		timeout: timeout,
	}
}

// NewCustomTemplateInspectParamsWithContext creates a new CustomTemplateInspectParams object
// with the ability to set a context for a request.
func NewCustomTemplateInspectParamsWithContext(ctx context.Context) *CustomTemplateInspectParams {
	return &CustomTemplateInspectParams{
		Context: ctx,
	}
}

// NewCustomTemplateInspectParamsWithHTTPClient creates a new CustomTemplateInspectParams object
// with the ability to set a custom HTTPClient for a request.
func NewCustomTemplateInspectParamsWithHTTPClient(client *http.Client) *CustomTemplateInspectParams {
	return &CustomTemplateInspectParams{
		HTTPClient: client,
	}
}

/* CustomTemplateInspectParams contains all the parameters to send to the API endpoint
   for the custom template inspect operation.

   Typically these are written to a http.Request.
*/
type CustomTemplateInspectParams struct {

	/* ID.

	   Template identifier
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the custom template inspect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomTemplateInspectParams) WithDefaults() *CustomTemplateInspectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the custom template inspect params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomTemplateInspectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the custom template inspect params
func (o *CustomTemplateInspectParams) WithTimeout(timeout time.Duration) *CustomTemplateInspectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the custom template inspect params
func (o *CustomTemplateInspectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the custom template inspect params
func (o *CustomTemplateInspectParams) WithContext(ctx context.Context) *CustomTemplateInspectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the custom template inspect params
func (o *CustomTemplateInspectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the custom template inspect params
func (o *CustomTemplateInspectParams) WithHTTPClient(client *http.Client) *CustomTemplateInspectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the custom template inspect params
func (o *CustomTemplateInspectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the custom template inspect params
func (o *CustomTemplateInspectParams) WithID(id int64) *CustomTemplateInspectParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the custom template inspect params
func (o *CustomTemplateInspectParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CustomTemplateInspectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
