// Code generated by go-swagger; DO NOT EDIT.

package docker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// StackImagesStatusReader is a Reader for the StackImagesStatus structure.
type StackImagesStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StackImagesStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStackImagesStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewStackImagesStatusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewStackImagesStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStackImagesStatusOK creates a StackImagesStatusOK with default headers values
func NewStackImagesStatusOK() *StackImagesStatusOK {
	return &StackImagesStatusOK{}
}

/*
StackImagesStatusOK describes a response with status code 200, with default header values.

Success
*/
type StackImagesStatusOK struct {
}

// IsSuccess returns true when this stack images status o k response has a 2xx status code
func (o *StackImagesStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this stack images status o k response has a 3xx status code
func (o *StackImagesStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stack images status o k response has a 4xx status code
func (o *StackImagesStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this stack images status o k response has a 5xx status code
func (o *StackImagesStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this stack images status o k response a status code equal to that given
func (o *StackImagesStatusOK) IsCode(code int) bool {
	return code == 200
}

func (o *StackImagesStatusOK) Error() string {
	return fmt.Sprintf("[GET /docker/{environmentId}/stacks/{id}/images_status][%d] stackImagesStatusOK ", 200)
}

func (o *StackImagesStatusOK) String() string {
	return fmt.Sprintf("[GET /docker/{environmentId}/stacks/{id}/images_status][%d] stackImagesStatusOK ", 200)
}

func (o *StackImagesStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStackImagesStatusBadRequest creates a StackImagesStatusBadRequest with default headers values
func NewStackImagesStatusBadRequest() *StackImagesStatusBadRequest {
	return &StackImagesStatusBadRequest{}
}

/*
StackImagesStatusBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type StackImagesStatusBadRequest struct {
}

// IsSuccess returns true when this stack images status bad request response has a 2xx status code
func (o *StackImagesStatusBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this stack images status bad request response has a 3xx status code
func (o *StackImagesStatusBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stack images status bad request response has a 4xx status code
func (o *StackImagesStatusBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this stack images status bad request response has a 5xx status code
func (o *StackImagesStatusBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this stack images status bad request response a status code equal to that given
func (o *StackImagesStatusBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *StackImagesStatusBadRequest) Error() string {
	return fmt.Sprintf("[GET /docker/{environmentId}/stacks/{id}/images_status][%d] stackImagesStatusBadRequest ", 400)
}

func (o *StackImagesStatusBadRequest) String() string {
	return fmt.Sprintf("[GET /docker/{environmentId}/stacks/{id}/images_status][%d] stackImagesStatusBadRequest ", 400)
}

func (o *StackImagesStatusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStackImagesStatusInternalServerError creates a StackImagesStatusInternalServerError with default headers values
func NewStackImagesStatusInternalServerError() *StackImagesStatusInternalServerError {
	return &StackImagesStatusInternalServerError{}
}

/*
StackImagesStatusInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type StackImagesStatusInternalServerError struct {
}

// IsSuccess returns true when this stack images status internal server error response has a 2xx status code
func (o *StackImagesStatusInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this stack images status internal server error response has a 3xx status code
func (o *StackImagesStatusInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this stack images status internal server error response has a 4xx status code
func (o *StackImagesStatusInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this stack images status internal server error response has a 5xx status code
func (o *StackImagesStatusInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this stack images status internal server error response a status code equal to that given
func (o *StackImagesStatusInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *StackImagesStatusInternalServerError) Error() string {
	return fmt.Sprintf("[GET /docker/{environmentId}/stacks/{id}/images_status][%d] stackImagesStatusInternalServerError ", 500)
}

func (o *StackImagesStatusInternalServerError) String() string {
	return fmt.Sprintf("[GET /docker/{environmentId}/stacks/{id}/images_status][%d] stackImagesStatusInternalServerError ", 500)
}

func (o *StackImagesStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
