// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DockerDashboardResponse docker dashboard response
//
// swagger:model docker.dashboardResponse
type DockerDashboardResponse struct {

	// containers
	Containers *DockerContainerStats `json:"containers,omitempty"`

	// images
	Images *DockerImagesCounters `json:"images,omitempty"`

	// networks
	Networks int64 `json:"networks,omitempty"`

	// services
	Services int64 `json:"services,omitempty"`

	// stacks
	Stacks int64 `json:"stacks,omitempty"`

	// volumes
	Volumes int64 `json:"volumes,omitempty"`
}

// Validate validates this docker dashboard response
func (m *DockerDashboardResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContainers(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImages(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DockerDashboardResponse) validateContainers(formats strfmt.Registry) error {
	if swag.IsZero(m.Containers) { // not required
		return nil
	}

	if m.Containers != nil {
		if err := m.Containers.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("containers")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("containers")
			}
			return err
		}
	}

	return nil
}

func (m *DockerDashboardResponse) validateImages(formats strfmt.Registry) error {
	if swag.IsZero(m.Images) { // not required
		return nil
	}

	if m.Images != nil {
		if err := m.Images.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("images")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("images")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this docker dashboard response based on the context it is used
func (m *DockerDashboardResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateContainers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateImages(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DockerDashboardResponse) contextValidateContainers(ctx context.Context, formats strfmt.Registry) error {

	if m.Containers != nil {

		if swag.IsZero(m.Containers) { // not required
			return nil
		}

		if err := m.Containers.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("containers")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("containers")
			}
			return err
		}
	}

	return nil
}

func (m *DockerDashboardResponse) contextValidateImages(ctx context.Context, formats strfmt.Registry) error {

	if m.Images != nil {

		if swag.IsZero(m.Images) { // not required
			return nil
		}

		if err := m.Images.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("images")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("images")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DockerDashboardResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DockerDashboardResponse) UnmarshalBinary(b []byte) error {
	var res DockerDashboardResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
