// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComPortainerPortainerEeAPIHTTPHandlerStatusStatus github com portainer portainer ee api http handler status status
//
// swagger:model github.com_portainer_portainer-ee_api_http_handler_status.status
type GithubComPortainerPortainerEeAPIHTTPHandlerStatusStatus struct {

	// Portainer API version
	// Example: 2.0.0
	Version string `json:"Version,omitempty"`

	// demo environment
	DemoEnvironment *GithubComPortainerPortainerEeAPIDemoEnvironmentDetails `json:"demoEnvironment,omitempty"`

	// Server Instance ID
	// Example: 299ab403-70a8-4c05-92f7-bf7a994d50df
	InstanceID string `json:"instanceID,omitempty"`
}

// Validate validates this github com portainer portainer ee api http handler status status
func (m *GithubComPortainerPortainerEeAPIHTTPHandlerStatusStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDemoEnvironment(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPortainerPortainerEeAPIHTTPHandlerStatusStatus) validateDemoEnvironment(formats strfmt.Registry) error {
	if swag.IsZero(m.DemoEnvironment) { // not required
		return nil
	}

	if m.DemoEnvironment != nil {
		if err := m.DemoEnvironment.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("demoEnvironment")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("demoEnvironment")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this github com portainer portainer ee api http handler status status based on the context it is used
func (m *GithubComPortainerPortainerEeAPIHTTPHandlerStatusStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDemoEnvironment(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComPortainerPortainerEeAPIHTTPHandlerStatusStatus) contextValidateDemoEnvironment(ctx context.Context, formats strfmt.Registry) error {

	if m.DemoEnvironment != nil {
		if err := m.DemoEnvironment.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("demoEnvironment")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("demoEnvironment")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComPortainerPortainerEeAPIHTTPHandlerStatusStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComPortainerPortainerEeAPIHTTPHandlerStatusStatus) UnmarshalBinary(b []byte) error {
	var res GithubComPortainerPortainerEeAPIHTTPHandlerStatusStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
