// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PortainerRegistry portainer registry
//
// swagger:model portainer.Registry
type PortainerRegistry struct {

	// Is authentication against this registry enabled
	// Example: true
	Authentication bool `json:"Authentication,omitempty"`

	// authorized teams
	AuthorizedTeams []int64 `json:"AuthorizedTeams"`

	// Deprecated fields
	// Deprecated in DBVersion == 18
	AuthorizedUsers []int64 `json:"AuthorizedUsers"`

	// Base URL or IP address of the ProGet registry
	// Example: registry.mydomain.tld:2375
	BaseURL string `json:"BaseURL,omitempty"`

	// gitlab
	Gitlab *PortainerGitlabRegistryData `json:"Gitlab,omitempty"`

	// Registry Identifier
	// Example: 1
	ID int64 `json:"Id,omitempty"`

	// management configuration
	ManagementConfiguration *PortainerRegistryManagementConfiguration `json:"ManagementConfiguration,omitempty"`

	// Registry Name
	// Example: my-registry
	Name string `json:"Name,omitempty"`

	// Password used to authenticate against this registry
	// Example: registry_password
	Password string `json:"Password,omitempty"`

	// team access policies
	TeamAccessPolicies PortainerTeamAccessPolicies `json:"TeamAccessPolicies,omitempty"`

	// Registry Type (1 - Quay, 2 - Azure, 3 - Custom, 4 - Gitlab, 5 - ProGet)
	// Enum: [1 2 3 4 5]
	Type int64 `json:"Type,omitempty"`

	// URL or IP address of the Docker registry
	// Example: registry.mydomain.tld:2375
	URL string `json:"URL,omitempty"`

	// user access policies
	UserAccessPolicies PortainerUserAccessPolicies `json:"UserAccessPolicies,omitempty"`

	// Username used to authenticate against this registry
	// Example: registry user
	Username string `json:"Username,omitempty"`
}

// Validate validates this portainer registry
func (m *PortainerRegistry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGitlab(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateManagementConfiguration(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTeamAccessPolicies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserAccessPolicies(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PortainerRegistry) validateGitlab(formats strfmt.Registry) error {
	if swag.IsZero(m.Gitlab) { // not required
		return nil
	}

	if m.Gitlab != nil {
		if err := m.Gitlab.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Gitlab")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Gitlab")
			}
			return err
		}
	}

	return nil
}

func (m *PortainerRegistry) validateManagementConfiguration(formats strfmt.Registry) error {
	if swag.IsZero(m.ManagementConfiguration) { // not required
		return nil
	}

	if m.ManagementConfiguration != nil {
		if err := m.ManagementConfiguration.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ManagementConfiguration")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ManagementConfiguration")
			}
			return err
		}
	}

	return nil
}

func (m *PortainerRegistry) validateTeamAccessPolicies(formats strfmt.Registry) error {
	if swag.IsZero(m.TeamAccessPolicies) { // not required
		return nil
	}

	if m.TeamAccessPolicies != nil {
		if err := m.TeamAccessPolicies.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("TeamAccessPolicies")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("TeamAccessPolicies")
			}
			return err
		}
	}

	return nil
}

var portainerRegistryTypeTypePropEnum []interface{}

func init() {
	var res []int64
	if err := json.Unmarshal([]byte(`[1,2,3,4,5]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		portainerRegistryTypeTypePropEnum = append(portainerRegistryTypeTypePropEnum, v)
	}
}

// prop value enum
func (m *PortainerRegistry) validateTypeEnum(path, location string, value int64) error {
	if err := validate.EnumCase(path, location, value, portainerRegistryTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PortainerRegistry) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("Type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *PortainerRegistry) validateUserAccessPolicies(formats strfmt.Registry) error {
	if swag.IsZero(m.UserAccessPolicies) { // not required
		return nil
	}

	if m.UserAccessPolicies != nil {
		if err := m.UserAccessPolicies.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("UserAccessPolicies")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("UserAccessPolicies")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this portainer registry based on the context it is used
func (m *PortainerRegistry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGitlab(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateManagementConfiguration(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTeamAccessPolicies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserAccessPolicies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PortainerRegistry) contextValidateGitlab(ctx context.Context, formats strfmt.Registry) error {

	if m.Gitlab != nil {
		if err := m.Gitlab.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Gitlab")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Gitlab")
			}
			return err
		}
	}

	return nil
}

func (m *PortainerRegistry) contextValidateManagementConfiguration(ctx context.Context, formats strfmt.Registry) error {

	if m.ManagementConfiguration != nil {
		if err := m.ManagementConfiguration.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ManagementConfiguration")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ManagementConfiguration")
			}
			return err
		}
	}

	return nil
}

func (m *PortainerRegistry) contextValidateTeamAccessPolicies(ctx context.Context, formats strfmt.Registry) error {

	if err := m.TeamAccessPolicies.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("TeamAccessPolicies")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("TeamAccessPolicies")
		}
		return err
	}

	return nil
}

func (m *PortainerRegistry) contextValidateUserAccessPolicies(ctx context.Context, formats strfmt.Registry) error {

	if err := m.UserAccessPolicies.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("UserAccessPolicies")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("UserAccessPolicies")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PortainerRegistry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PortainerRegistry) UnmarshalBinary(b []byte) error {
	var res PortainerRegistry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
