// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PortainereeEdgeConfigProgress portaineree edge config progress
//
// swagger:model portaineree.EdgeConfigProgress
type PortainereeEdgeConfigProgress struct {

	// success
	Success int64 `json:"success,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this portaineree edge config progress
func (m *PortainereeEdgeConfigProgress) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this portaineree edge config progress based on context it is used
func (m *PortainereeEdgeConfigProgress) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PortainereeEdgeConfigProgress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PortainereeEdgeConfigProgress) UnmarshalBinary(b []byte) error {
	var res PortainereeEdgeConfigProgress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
