// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PortainereeEnvironmentEdgeSettings portaineree environment edge settings
//
// swagger:model portaineree.EnvironmentEdgeSettings
type PortainereeEnvironmentEdgeSettings struct {

	// The command list interval for edge agent - used in edge async mode [seconds]
	// Example: 60
	CommandInterval int64 `json:"CommandInterval,omitempty"`

	// The ping interval for edge agent - used in edge async mode [seconds]
	// Example: 60
	PingInterval int64 `json:"PingInterval,omitempty"`

	// The snapshot interval for edge agent - used in edge async mode [seconds]
	// Example: 60
	SnapshotInterval int64 `json:"SnapshotInterval,omitempty"`

	// Whether the device has been started in edge async mode
	AsyncMode *bool `json:"asyncMode,omitempty"`
}

// Validate validates this portaineree environment edge settings
func (m *PortainereeEnvironmentEdgeSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this portaineree environment edge settings based on context it is used
func (m *PortainereeEnvironmentEdgeSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PortainereeEnvironmentEdgeSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PortainereeEnvironmentEdgeSettings) UnmarshalBinary(b []byte) error {
	var res PortainereeEnvironmentEdgeSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
