// Code generated by go-swagger; DO NOT EDIT.

package endpoints

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// EndpointDeleteReader is a Reader for the EndpointDelete structure.
type EndpointDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EndpointDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewEndpointDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEndpointDeleteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewEndpointDeleteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEndpointDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEndpointDeleteNoContent creates a EndpointDeleteNoContent with default headers values
func NewEndpointDeleteNoContent() *EndpointDeleteNoContent {
	return &EndpointDeleteNoContent{}
}

/* EndpointDeleteNoContent describes a response with status code 204, with default header values.

Success
*/
type EndpointDeleteNoContent struct {
}

func (o *EndpointDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /endpoints/{id}][%d] endpointDeleteNoContent ", 204)
}

func (o *EndpointDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndpointDeleteBadRequest creates a EndpointDeleteBadRequest with default headers values
func NewEndpointDeleteBadRequest() *EndpointDeleteBadRequest {
	return &EndpointDeleteBadRequest{}
}

/* EndpointDeleteBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type EndpointDeleteBadRequest struct {
}

func (o *EndpointDeleteBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /endpoints/{id}][%d] endpointDeleteBadRequest ", 400)
}

func (o *EndpointDeleteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndpointDeleteNotFound creates a EndpointDeleteNotFound with default headers values
func NewEndpointDeleteNotFound() *EndpointDeleteNotFound {
	return &EndpointDeleteNotFound{}
}

/* EndpointDeleteNotFound describes a response with status code 404, with default header values.

Environment(Endpoint) not found
*/
type EndpointDeleteNotFound struct {
}

func (o *EndpointDeleteNotFound) Error() string {
	return fmt.Sprintf("[DELETE /endpoints/{id}][%d] endpointDeleteNotFound ", 404)
}

func (o *EndpointDeleteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewEndpointDeleteInternalServerError creates a EndpointDeleteInternalServerError with default headers values
func NewEndpointDeleteInternalServerError() *EndpointDeleteInternalServerError {
	return &EndpointDeleteInternalServerError{}
}

/* EndpointDeleteInternalServerError describes a response with status code 500, with default header values.

Server error
*/
type EndpointDeleteInternalServerError struct {
}

func (o *EndpointDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /endpoints/{id}][%d] endpointDeleteInternalServerError ", 500)
}

func (o *EndpointDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
